iTwin/imodel-native

- iModelJsNodeAddon/IModelJsNative.h
- iModelJsNodeAddon/JsInterop.cpp
- iModelJsNodeAddon/api_package/ts/src/test/DgnDb.test.ts
- iModelJsNodeAddon/api_package/ts/src/test/index.ts
These extra schema search paths are all the paths we currently add schemas to in the node addon. This PR resolves a long-standing bug where importing a schema results in us being potentially unable to find any of its referenced schemas. This bug was hidden by the fact that most of our iModels already contained the referenced BisCore schema (version 01.00.00) in PresentationRules.ecschema. Since PresentationRules.ecschema now references a newer version of the BisCore schema (01.00.15) which our iModels (atleast the seed files in presentation tests) didn't have, this bug showed up. Even though the BisCore schema at version 01.00.15 was packaged in the node addon, it was unable to be found when importing the PresentationRules schema, because we've never told the schemaLocaters to look in the …
> Add more schema search paths when importing schemas

- iModelCore/iModelPlatform/DgnCore/DgnDomain.cpp
- iModelCore/iModelPlatform/Tests/DgnProject/ECSchemas/SchemaVersionTest.02.02.06.ecschema.xml
- iModelCore/iModelPlatform/Tests/DgnProject/ECSchemas/SchemaVersionTest.02.02.07.ecschema.xml
- iModelCore/iModelPlatform/Tests/DgnProject/ECSchemas/TestSchema.01.00.00.ecschema.xml
- iModelCore/iModelPlatform/Tests/DgnProject/NonPublished/SchemaVersion_Test.cpp
When the status of registered domain is `SchemaUpgradeRecommended` and on its one of reference schema's we get `SchemaNotFound` status then in this case we should be returning the same status as domain schema. 
TS: 4682
> DgnDomain SchemaUpgradeRequired Fix

- iModelCore/ECPresentation/Tests/NonPublished/Helpers/TestHelpers.cpp
- iModelCore/ECPresentation/Tests/NonPublished/Helpers/TestHelpers.h
- iModelCore/ECPresentation/Tests/NonPublished/Integration/Hierarchies/HierarchiesWithRulesetVariablesTests.cpp
- iModelCore/ECPresentation/Tests/NonPublished/Integration/Hierarchies/HierarchyIntegrationTests.cpp
- iModelCore/ECPresentation/Tests/NonPublished/Integration/PresentationManagerIntegrationTests.cpp
- iModelCore/ECPresentation/Tests/NonPublished/Integration/PresentationManagerIntegrationTests.h
Add an API to conveniently validate produced hierarchies in our integration tests. I only refactored ruleset variables - related integration tests for now.
> Presentation: API for convenient hierarchy validation

- iModelCore/ECDb/ECDb/RemapManager.cpp
- iModelCore/ECDb/ECDb/RemapManager.h
- iModelCore/ECDb/ECDb/SchemaManagerDispatcher.cpp
- iModelCore/ECDb/Tests/NonPublished/SchemaRemapTests.cpp
Basically, when we reload schemas after SchemaWriter is done, we did not load the full set of affected schemas, but only the ones included in the import. So the .DerivedClasses() call used by the mapping code did not traverse to all leaf classes.
My fix is to just load all affected schemas before this step happens. No need to explicitly call Mapping on them, it's enough if they are loaded.
Also with this I want to push some logic which allows dumping schemas used during a schema import to be written to Disk. This code has been quite useful in the past and I find myself adding and deleting it many times. I've placed it into #ifndef NDEBUG just like our BeAssert acts, and it requires an environment variable to be set.
> Fix schema import not properly mapping properties in affected schemas that are not part of the import

- iModelCore/ECPresentation/Source/Content/ContentProviders.cpp
- iModelCore/ECPresentation/Source/Hierarchies/NavNodeProviders.cpp
- iModelCore/ECPresentation/Source/Shared/RulesDrivenProviderContext.cpp
- iModelCore/ECPresentation/Source/Shared/RulesDrivenProviderContext.h
- iModelCore/ECPresentation/Tests/NonPublished/Unit/Hierarchies/MultiSpecificationNodesProviderTests.cpp
The problem showed up when we had multiple data sources under the same hierarchy level in that case every subsequent data source was associated with variables of all previous data sources.
> Presentation: Fix unnecessary data source association with ruleset vars

- iModelJsNodeAddon/IModelJsNative.cpp
- iModelJsNodeAddon/api_package/ts/src/NativeLibrary.ts
- iModelJsNodeAddon/api_package/ts/src/test/SqlStatement.test.ts
Instead of 2 methods there is now only one which returns undefined if no origin property is available
> Changed getOriginPropertyName signature to improve usability

- iModelCore/Bentley/Bentley/nonport/BeStringUtilities.cpp
- iModelCore/Bentley/Tests/NonPublished/Utf8PrintfStringTests.cpp
> Fix a crash in `Utf8PrintfString::CreateFromVaList` for long strings on unit systems

- iModelCore/BeSQLite/SQLite/UpdateSqlite.bat
- iModelCore/BeSQLite/SQLite/shell.c
- iModelCore/BeSQLite/SQLite/sqlite3.h
SQLite updated from [itwin-sqlite-v3.40.0-r0](https://github.com/iTwin/sqlite/releases/tag/itwin-sqlite-v3.40.0-r0)
Update SQLite to `v3.40.0` with the following additional changes from master. 
* [Fix a comment in ext/session/test_session.c.](https://github.com/iTwin/sqlite/commit/11c5a1292b7925e85afc6bdf7016ee9642061591)
* [Prevent the sessions rebaser from generating changesets containing UP…](https://github.com/iTwin/sqlite/commit/8a9a5d971d2c02fce4209fac933d4182e5139e65)
Also updated UpdateSqlite.bat to update source from https://github.com/iTwin/sqlite fork.
> Update SQLite to v3.40.0 and include fix for changeset generated by old code fail to apply.

- iModelCore/BeSQLite/CloudSqlite.cpp
- iModelCore/BeSQLite/PublicAPI/BeSQLite/CloudSqlite.h
- iModelCore/BeSQLite/SQLite/blockcachevfs.c
- iModelJsNodeAddon/IModelJsNative.h
- iModelJsNodeAddon/JsCloudSqlite.cpp
- iModelJsNodeAddon/api_package/ts/src/NativeCloudSqlite.ts
The current default in SQLite code is 600 seconds. 
This will improve performance in cases where we do timeout when receiving blocks. There are some examples in the v2 checkpoint agent, which show upwards of 10 minutes wasted on a single request. These requests will get retried more quickly if we hit our timeout faster.
I opted for 60 seconds as the default, but lower may be even more beneficial especially in write cases. As a faster http timeout could mean a client releases the write lock faster.
> CloudSQLite: add support for httptimeout being configurable

- iModelCore/BeSQLite/SQLite/UpdateSqlite.bat
- iModelCore/BeSQLite/SQLite/bentley-sqlite.c
- iModelCore/BeSQLite/SQLite/shell.c
- iModelCore/BeSQLite/SQLite/sqlite3.h
cherry-pick
f6d591426653d6c4edef06532e2a345bb2d1cbfe
Update SQLite to v3.40.0 and include fix for changeset generated by old code fail to apply. (#76)
8c335544df909a6d74f0b9405adf48b28c8870df
fix build error (#78)
Co-authored-by: Affan Khan <khanaffan@users.noreply.github.com>
> Update SQLite to v3.40.0 and include fix for changeset generated by old code fail to apply

- iModelCore/ECPresentation/Source/Hierarchies/NavNodeProviders.cpp
- iModelCore/ECPresentation/Tests/NonPublished/Integration/Hierarchies/HierarchyIntegrationTests.cpp
After changes to not cache transient node data we now need to evaluate node artifacts when loading nodes from cache. Previously artifacts were evaluated only when querying nodes based on specification. This change inverts this logic to always try to load artifacts unless we now that there are no artifact rules for specification used to query nodes.
> Presentation: Evaluate node artifacts when taking node from cache

- iModelCore/ecobjects/src/ExpressionHandler.cpp
- iModelCore/libsrc/compress/lzma/lzma.mke
- iModelCore/libsrc/compress/lzma19/lzma.mke
- iModelCore/libsrc/compress/prewire.mke
- iModelCore/libsrc/compress/snappy/snappy.mke
- iModelCore/libsrc/compress/zlib/Zlib.mke
- iModelJsNodeAddon/api_package/ts/makeTs.mke
- iModelJsNodeAddon/api_package/ts/runTests.mke
- schemas/BisSchemas/findSchemaPath.mki
- schemas/ECStandards/StandardSchemas.delivery.mki
- schemas/ECStandards/StandardSchemas.prewire.mke
- schemas/ECStandards/V3ConversionSchemas.prewire.mke
This is the next step to removing dependence on node committed to repositories. Run the installed npm rather than the one in the repository. This only affects the building and running of the tests imodeljsnodeaddon. Also cleaned up some copyright headers.
> Relying on installed/pipeline node rather than repo

- .github/CODEOWNERS
- iModelCore/GeomLibs/geom/src/CurvePrimitive/cv_ops.cpp
- iModelCore/GeomLibs/geom/test/CurvePrimitiveTest/t_CurvePrimitive.cpp
Enhance `CurveVector::GetAnyFrenetFrame` with line string logic that seeks an optimal frame among the points, preferring the first frame if it is good enough.
Details:
* This is a backport from PowerPlatform, as requested by @swwilson-bsi.
* I also updated geomlibs owners.
> stable Frenet frame logic for line strings

- iModelCore/ECPresentation/Source/TaskScheduler.h
- iModelCore/ECPresentation/Tests/NonPublished/Unit/TasksSchedulerTests.cpp
- iModelCore/ECPresentation/Tests/Stress/TaskManagerStressTests.cpp
Resolves https://github.com/iTwin/imodel-native/issues/47.
This PR contains 2 fixes for tasks-related issues and stress test enhancements to reproduce them both.
- Crash when cancelling a `Future` chained to a destroyed task (https://sentry.io/organizations/bentley-systems-inc/issues/3802676977). [Fix](https://github.com/iTwin/imodel-native/commit/ccb3198df569294557b0cc766faf06fba6399ab1).
- Crash when a `Promise`, chained to our produced `Future`, is completed after destroying `ECPresentationTasksManager` (https://github.com/iTwin/imodel-native/issues/47). [Fix](https://github.com/iTwin/imodel-native/commit/e28583c46ad696cca386a192a522f077c287968f).
> Presentation: Fix multithreading issues

- iModelCore/ECPresentation/Source/TaskScheduler.h
- iModelCore/ECPresentation/Tests/NonPublished/Unit/TasksSchedulerTests.cpp
- iModelCore/ECPresentation/Tests/Stress/TaskManagerStressTests.cpp
Backport https://github.com/iTwin/imodel-native/pull/98 (the fixed issues have a decent chance of being reproduced in production code).
* Can't use our executor for chained tasks, because they may exceed the lifetime of the executor
* Can't use `m_mutex` in interrupt handler as the task may be destroyed. Using `mutex` is allowed, because it stays valid for the lifetime of all tasks.
> Presentation: Fix multithreading issues (#98)

- iModelCore/GeomLibs/geom/src/funcs/ConvexHull.cpp
- iModelCore/GeomLibs/geom/src/regions/rg_gaps.cpp
- iModelCore/GeomLibs/geom/test/CurvePrimitiveTest/t_frustum.cpp
Cherry-pick of #92 
Details:
* Longstanding oob error caused by incomplete buffer -> bvector conversion
* ConvexHullXY closure point logic appended last point instead of first
> cherry-pick: fix out-of-bounds array deref caught by asan

- iModelCore/ECDb/ECDb/SchemaManagerDispatcher.cpp
- affects optional debug only code
- fixes debug building on linux (`getenv_s` is a microsoft extension)
- assumes the security benefits of `getenv_s` aren't necessary since this code doesn't exist in release/NDEBUG versions
> don't use getenv_s in conditional debug code since it doesn't exist on linux

- iModelCore/iModelPlatform/DgnCore/CodeSpec.cpp
- iModelCore/iModelPlatform/DgnCore/DgnElement.cpp
- iModelCore/iModelPlatform/DgnCore/DgnElements.cpp
- iModelCore/iModelPlatform/PublicAPI/DgnPlatform/DgnDbTables.h
- iModelCore/iModelPlatform/PublicAPI/DgnPlatform/DgnElement.h
- iModelCore/iModelPlatform/Tests/DgnProject/NonPublished/DgnElement_Test.cpp
- iModelJsNodeAddon/JsInteropDgnDb.cpp
The value of `CodeScope` *must* be a valid ElementId, but we did not enforce that. Throw an exception if the supplied value is illegal.
On insert and update, the value supplied from JavaScript may be a `FederationgGuid`. If so, look up the element and use its ElementId.
> Validate that CodeScope is the ElementId of an existing element

- iModelCore/GeomLibs/geom/src/bspline/bspsurfacetrim.cpp
- iModelCore/GeomLibs/geom/src/polyface/PolyfaceStitch.cpp
New version of clang caught a few more.
> geomlibs: remove more unused-but-set vars

- iModelCore/BeSQLite/CloudSqlite.cpp
Opening a CloudSqlite iModel wasn't working correctly. 
Integration test was failing. https://github.com/iTwin/itwinjs-core/pull/4942
> set fromContainer flag correctly

- iModelCore/ECPresentation/Source/Hierarchies/HierarchiesFiltering.cpp
- iModelCore/ECPresentation/Tests/NonPublished/Integration/Hierarchies/Hierarchies_InstanceFiltering.cpp
Note: this likely requires regenerating presentation-full-stack-test snapshots. Will do that a bit later, will then associate this PR with snapshot update PR.
> Presentation: Should not support filtering nodes built with `parent` symbol

- iModelCore/ECPresentation/Source/Content/ContentSpecificationsHandler.cpp
- iModelCore/ECPresentation/Tests/NonPublished/Integration/Content/ContentIntegrationTests.cpp
Bug introduced with https://github.com/iTwin/imodel-native/pull/124, revealed by `presentation-full-stack-tests` in `itwinjs-core`.
> Presentation: Fix polymorphic properties handling with customization rules

- iModelCore/ECPresentation/Source/Hierarchies/NavigationQueryBuilder.cpp
- iModelCore/ECPresentation/Tests/NonPublished/Integration/Hierarchies/Hierarchies_InstanceFiltering.cpp
When creating the filter definition, we only set either target class or relationship alias, leaving the other one empty. The query builder expects both to be set, so we have to make sure that's the case.
> Presentation: Fix hierarchy level filtering with related instances

- iModelCore/ECDb/ECDb/SchemaManagerDispatcher.cpp
- iModelCore/ECDb/ECDb/SchemaManagerDispatcher.h
- iModelCore/ECDb/Tests/NonPublished/DbMappingTests.cpp
Make the error message more informative when attempting to create or alter a table with too many columns. The error message now includes information about the class that failed to import, and the maximum number of columns a table can have.
> Improve error message for 'too many columns' error

- iModelCore/BeSQLite/SQLite/bcvutil.c
- iModelCore/BeSQLite/SQLite/blockcachevfs.c
'Do not error out if a path passed to sqlite3_bcv_download() or similar contains one or more components that are symbolic links'
> CloudSQLite: Do not error out if a path contains a symlink

- build/azure-pipelines.yml
The pipeline uses templates from a repo that was not included in this pipeline's resources. Adds the missing repository resources to fix the build.
> Add missing repository resources to pipeline

- iModelJsNodeAddon/presentation/ECPresentationSerializer.cpp
Send full name of persistence unit for looking it up later on the frontend.
> Use full name of persistence unit when serializing KOQ info

- iModelCore/BeSQLite/SQLite/bcv_int.h
- iModelCore/BeSQLite/SQLite/bcvutil.c
- iModelCore/BeSQLite/SQLite/blockcachevfs.c
Fix for the abort that Mike stumbled upon when running node with the cpu profiler. This doesn't fix the root issue, just exits gracefully when the issue occurs.
https://sqlite.org/cloudsqlite/info/744d952b109a61b8d0ed
> Ensure that bcvfsDispatchRunAll() issues callbacks for all pending jobs before returning

- iModelCore/Bentley/Bentley.PartFile.xml
- iModelCore/GeomLibs/geomlibs.PartFile.xml
- iModelCore/Units/Units.PartFile.xml
- iModelCore/ecobjects/ECObjects.PartFile.xml
- iModelCore/iModelPlatform/iModelPlatform.PartFile.xml
- iModelCore/libsrc/libjpegturbo/vendor/config.h
- iModelCore/libsrc/libjpegturbo/vendor/jconfig.h
- iModelJsNodeAddon/iModelJsNodeAddon.PartFile.xml
This will allow us to build imodeljsnodeaddon with mobile OS's and have it just build the imodelcore portion. Also cleaned up some additional partfile stuff and fixed some file headers.
> Locked the imodeljsnodeaddon build to just Win, Linux, and MacOS x64/Arm

- iModelCore/iModelPlatform/iModelPlatform.PartFile.xml
The attribute is required for `bb taglist` command. 
**Note:** The build has started failing with error: `PrgOutputDir does not exist for part RunIModelEvolutionTests. It is needed for the name of the tag file`
> PrgOutputDir is defined

- iModelCore/ECPresentation/Source/Hierarchies/NavigationQueryBuilder.cpp
Introduced with https://github.com/iTwin/imodel-native/pull/187.
Only fails in DEBUG builds because of assertion failure. CI uses optimized builds, which don't do assertions.
> Presentation: Fix test failures in debug builds

- iModelCore/BeSQLite/BeSQLite.PartFile.xml
- iModelCore/BeSQLite/BeSQLite.mke
- iModelCore/BeSQLite/PublicAPI/BeSQLite/BeSQLite.h
- iModelCore/Bentley/BeRapidJson/PublicAPI/BeRapidJson/BeJsValue.h
- iModelCore/Bentley/Bentley.PartFile.xml
- iModelCore/ECPresentation/ECPresentation.PartFile.xml
- iModelCore/GeoCoord/GeoCoord.PartFile.xml
- iModelCore/GeoCoord/PublicAPI/GeoCoord/BaseGeoCoord.h
- iModelCore/GeomLibs/PublicAPI/GeomJsonWireFormat/BeJsGeomUtils.h
- iModelCore/GeomLibs/PublicAPI/GeomSerialization/GeomLibsJsonSerialization.h
- iModelCore/GeomLibs/geomlibs.PartFile.xml
- iModelCore/Units/PublicAPI/Formatting/FormattingApi.h
- iModelCore/Units/Units.PartFile.xml
- iModelCore/ecobjects/PublicApi/ECObjects/ECJsonUtilities.h
- iModelCore/ecobjects/PublicApi/ECObjects/ECSchema.h
- iModelCore/ecobjects/PublicApi/ECObjects/ECUnit.h
- iModelCore/iModelPlatform/PublicAPI/DgnPlatform/DgnElement.h
- iModelCore/iModelPlatform/Tests/DgnProject/NonPublished/ExternalSource_Test.cpp
- iModelCore/iModelPlatform/iModelPlatform.PartFile.xml
- iModelCore/libsrc/jsoncpp/BeJsonCpp.PartFile.xml
- iModelCore/libsrc/jsoncpp/tests/NonPublished/BeJsonUtilitiesTests.cpp
- node-addon-api/Napi/napi.h
- node-addon-api/node-addon-api.PartFile.xml
Related to https://github.com/iTwin/itwinjs-backlog/issues/444#issuecomment-1454712836.
This PR inverts the dependency between `BeRapidJson` and `BeJsonCpp` parts - previously `BeJsonCpp` had a `BeRapidJson` dependency and now it's the opposite. 
I initially tried to avoid making `BeRapidJson` depend on `BeJsonCpp`, but that required removing jsoncpp-related implicit constructors from `BeJsConst` and `BeJsValue`. That broke tons of code across the whole repository in places where `jsoncpp` is still used... I believe we need to first get rid of `jsoncpp` usages before removing this dependency.
> Move `BeJsValue.h` away from `jsoncpp`

- iModelCore/ECPresentation/Tests/valgrind.supp
Add a suppression for the following:
https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=1995386&view=logs&j=502f68b3-17c3-5e6e-19b1-e8b7c76cdbb4&t=626d5962-b3fb-584d-1451-aeaa2b305f7d&l=5412
```
==4378==    by 0x5044189: allocate_stack (allocatestack.c:584)
==4378==    by 0x5044189: pthread_create@@GLIBC_2.2.5 (pthread_create.c:663)
==4378==    by 0x197427A: BentleyM0200::BeThreadUtilities::StartNewThread(void* (*)(void*), void*, int) (BeThread.cpp:351)
==4378==    by 0x19563EA: Start (BeFolly.cpp:84)
==4378==    by 0x19563EA: BeFolly::ThreadPool::ThreadPool(int, char const*) (BeFolly.cpp:99)
==4378==    by 0x195ADCA: CpuThreadPoolImp (BeFolly.cpp:162)
==4378==    by 0x195ADCA: operator() (Singleton.h:563)
==4378==    by 0x195ADCA: std::_Function_handler<(anonymous …
```
> Presentation: Add valgrind suppression for `ThreadPool::GetCpuPool()`

- iModelCore/ECPresentation/Source/UpdateHandler.cpp
- iModelJsNodeAddon/presentation/ECPresentationSerializer.cpp
- iModelJsNodeAddon/presentation/UiStateProvider.cpp
- iModelJsNodeAddon/presentation/UiStateProvider.h
Fixed some problems that caused hierarchy update to stop working:
- Changed UIState lookup to use Connection Id
- Fixed ECPresentationSerializer to correctly parse strings
- Reintroduced parent node lookup logic during update that was removed with changes adding hierarchy filtering.
> Presentation: Fix hierarchy update

- iModelCore/BeSQLite/SQLite/UpdateCloudSqlite.bat
- iModelCore/BeSQLite/SQLite/bcv_int.h
- iModelCore/BeSQLite/SQLite/bcvmodule.c
- iModelCore/BeSQLite/SQLite/bcvmodule.h
- iModelCore/BeSQLite/SQLite/bcvutil.c
- iModelCore/BeSQLite/SQLite/blockcachevfs.c
- iModelCore/BeSQLite/SQLite/blockcachevfsd.c
- iModelJsNodeAddon/JsCloudSqlite.cpp
- iModelJsNodeAddon/api_package/ts/package-lock.json
- iModelJsNodeAddon/api_package/ts/src/NativeLibrary.ts
Write locks for CloudContainers expire after a duration (usually an hour). Previously the times were dependent on local computer times, leading to the dependence that they all be relatively in sync. 
This PR includes a change from SQLite.org to use the time from the server, so expiration duration is not ambiguous and does not use local computer times at all.
> Use server time rather than local computer time for write lock expiration

- iModelCore/iModelPlatform/Tests/DgnProject/Compatibility/CompatibilityRunner/PullNugets.py
The new test runner contains the fix for the conflicting change pushed in the tests setup with last profile upgrade. For more details see PR: https://github.com/iTwin/imodel-native/commit/75b43e072dbfc928a2fdee0d644c61bf18b66090
> Consume New Test Runner and Files

- iModelCore/ECPresentation/PublicAPI/ECPresentation/Content.h
- iModelCore/ECPresentation/PublicAPI/ECPresentation/DefaultECPresentationSerializer.h
- iModelCore/ECPresentation/PublicAPI/ECPresentation/ECPresentationTypes.h
- iModelCore/ECPresentation/PublicAPI/ECPresentation/IECPresentationSerializer.h
- iModelCore/ECPresentation/Source/Content/Content.cpp
- iModelCore/ECPresentation/Source/Content/ContentItemBuilder.cpp
- iModelCore/ECPresentation/Source/Content/ContentItemBuilder.h
- iModelCore/ECPresentation/Source/Content/ContentProviders.cpp
- iModelCore/ECPresentation/Source/Content/ContentQueryResultsReader.cpp
- iModelCore/ECPresentation/Source/Serialization/DefaultECPresentationSerializer.cpp
- iModelCore/ECPresentation/Tests/NonPublished/Integration/Content/ContentIntegrationTests.h
- iModelCore/ECPresentation/Tests/NonPublished/Integration/Content/Content_RelatedPropertiesTests.cpp
- iModelJsNodeAddon/IModelJsNative.cpp
- iModelJsNodeAddon/presentation/ECPresentationSerializer.cpp
- iModelJsNodeAddon/presentation/ECPresentationSerializer.h
- iModelJsNodeAddon/presentation/ECPresentationUtils.cpp
Added instance label to raw navigation property value. This is necessary for formatting content values on frontend.
Added ability to omit formatted display values from Content response.
itwinjs-core: https://github.com/iTwin/itwinjs-core/tree/presentation/values_formatting
TS changes: https://github.com/iTwin/itwinjs-core/pull/5303
Part of https://github.com/iTwin/itwinjs-core/issues/5029
> Presentation: Add label to navigation property value

- iModelCore/ECDb/ECDb/SchemaManagerDispatcher.cpp
- iModelCore/ECDb/Tests/NonPublished/DbMappingTests.cpp
- iModelJsNodeAddon/api_package/ts/assets/test/test-with-overflow.text
- iModelJsNodeAddon/api_package/ts/src/test/DgnDb.test.ts
The issue happens if iModel has an overflow table. Schema import always runs instance upgrade on all classes that are mapped overflow table.
> Profile upgrade fails due to a data transformation is detected where there is none

- iModelJsNodeAddon/IModelJsNative.cpp
- iModelJsNodeAddon/presentation/ECPresentationUtils.cpp
- iModelJsNodeAddon/presentation/ECPresentationUtils.h
When looking into https://github.com/iTwin/presentation-performance-tests/issues/68, found that we're not reporting diagnostics when the request fails. Which is when they're actually important...
itwinjs-core PR: https://github.com/iTwin/itwinjs-core/pull/5375
itwinjs-core: https://github.com/iTwin/itwinjs-core/tree/presentation/report-diagnostics-with-error-responses
> Presentation: Include diagnostics in error responses

- iModelJsNodeAddon/IModelJsNative.cpp
- iModelJsNodeAddon/presentation/ECPresentationUtils.cpp
- Before sending the response flush logs that accumulated while handling the request.
- Call `CreateConnection` within a diagnostics scope, otherwise some logs get lost.
> Presentation: Logging improvements

- iModelCore/iModelPlatform/DgnCore/SnapContext.cpp
As the geometry stream is created from json as if it were a part, in order to not require a category, and parts don't support subcategory changes, it could result in decoration geometry that wasn't snappable. The supplier of the non-element geometry should only include geometry for the appropriate subcategory according to the HitDetail so there isn't any need for filtering on the backend.
> Ignore subcategory for non-element geometry

- iModelCore/BeSQLite/SQLite/blockcachevfsd.c
Currently backends are owner of all files listed in below screenshot:
with this PR: They will instead be owners of only the files in the red rectangle. Orchestrator team will do necessary work on their end to make sure of that. 
When we get to a point where all backends are on 4.x, then we can further restrict permissions so that backends only need read access to the imodelblocks-* folders. This is because we had an earlier update from SQLite team which makes it so backends no longer need to write to those folders.
> CloudSQLite: Change permissions of directories created by the cloudsqlite daemon

- iModelCore/BeSQLite/CloudSqlite.cpp
- iModelCore/BeSQLite/PublicAPI/BeSQLite/CloudSqlite.h
- iModelJsNodeAddon/JsCloudSqlite.cpp
The JavaScript callbacks for containers weren't being called when containers are automatically disconnected by `CloudCache.destroy`. The symptom was that tests that clear an interval timer in `onDisconnected` hang for 5 seconds on exit with the message:
```cmd
ERROR: Handle leak detected. Node was still running 5 seconds after tests completed.
```
> Call `onDisconnect` and `onDisconnected` from Cache::Destroy

- iModelCore/ECPresentation/Source/Shared/Queries/PresentationQuery.cpp
- iModelCore/ECPresentation/Tests/NonPublished/Unit/Queries/NavigationQueryTests.cpp
Closes: https://github.com/iTwin/imodel-native/issues/247
`ComplexQueryBuilderTests.ToString_OuterJoin_MultiClauses_WithRelationshipWithoutNavigationPropertiesAndWithMultiNavigationPropertiesInside` test describes the fix.
Before the fix we would have had this query string.
Before:
```
FROM ONLY [alias_schema_name].[A] [this]
LEFT JOIN (
SELECT [rel_ab_alias].*
FROM [alias_schema_name].[A_Has_B] [rel_ab_alias]
INNER JOIN [alias_schema_name].[B] [b_alias] ON [b_alias].[ECInstanceId] = [rel_ab_alias].[TargetECInstanceId]
) [rel_ab_alias] ON [this].[ECInstanceId] = [rel_ab_alias].[SourceECInstanceId]
LEFT JOIN [alias_schema_name].[B] [b_alias] ON [b_alias].[ECInstanceId] = [rel_ab_alias].[TargetECInstanceId]
LEFT JOIN [alias_schema_name].[C] [c_alias] ON [c_alias].[ECInstanceId] = …
```
> Presentation: Avoid joining relationship if navigation property is available

- iModelJsNodeAddon/IModelJsNative.cpp
- iModelJsNodeAddon/api_package/ts/src/NativeLibrary.ts
- iModelJsNodeAddon/presentation/ECPresentationUtils.cpp
- iModelJsNodeAddon/presentation/ECPresentationUtils.h
Related to https://github.com/iTwin/imodel-native/issues/275. 
The change doesn't fix the problem altogether, but makes the request:
- fail instead of crashing the whole backend,
- require less peak memory,
- slightly quicker as we don't need to copy the string which may sometimes be massive (100+ MB).
The consolidated descriptor request will still fail for the iModel mentioned in the Sentry report due to massive amount of duplicated aspects in the iModel. The request is to load all properties of all aspects and the response is 700+ MB serialized JSON string. Node supports up to 512 MB strings and fails. 
itwinjs-core PR: https://github.com/iTwin/itwinjs-core/pull/5534
itwinjs-core: https://github.com/iTwin/itwinjs-core/tree/presentation/accept-buffer-responses-from-addon
> Presentation: Set serialized responses as `Napi::Buffer` to avoid copying native string to `Napi::String`

- iModelCore/ECDb/Tests/BackDoor/PublicAPI/BackDoor/ECDb/TestInfoHolders.h
- iModelCore/GeomLibs/PublicAPI/Geom/capi/polygondecomp_capi.h
Using clang 13, 14, or 15 on ubuntu 22.04 to build locally. I observe errors where code is trying to declare a class member of type `vector<T>` where `T` is an incomplete (forward-declared) type. AFAICT this is a correctly-reported error per C++20.
Fix is easy, though I question why an alleged "C API" uses `vector` at all.
@MichaelBelousov observes the same. @markschlosseratbentley for some reason does not.
CI does not. Unclear why. It's using clang 13. I'd be interested to know what version of libstdc++ it's using.
> Fix clang ubuntu build

- iModelCore/iModelPlatform/Tests/DgnProject/NonPublished/ChangeTestFixture.cpp
This was an oversight during previous PR. The comment just clarifies intent of one test.
> Added explanation for commented Apply_Changeset test

- iModelCore/Bentley/PublicAPI/Bentley/BeVersion.h
- iModelCore/Bentley/Tests/NonPublished/VersionTests.cpp
The validation was added in [PR#301](https://github.com/iTwin/imodel-native/pull/301) a day ago, before we did not validate the string at all.
But it turns out people use the method with and without custom format strings with less than 4 digits.
These changes should fix that scenario.
Also added tests.
> Made BeVersion.FromString validation less strict

- iModelCore/ECPresentation/Source/Hierarchies/NavigationQueryContracts.cpp
- iModelCore/ECPresentation/Source/Shared/ECSchemaHelper.cpp
Closes: https://github.com/iTwin/imodel-native/issues/299
itwinjs-core: https://github.com/iTwin/itwinjs-core/tree/presentation/query-contains-names-from-sqlite-keywords
> Presentation: Failure to produce content when query contains classes with names from SQLite reserved keywords

- iModelCore/BeSQLite/PublicAPI/BeSQLite/BeSQLite.h
- iModelCore/iModelPlatform/DgnCore/DgnDomain.cpp
- iModelCore/iModelPlatform/DgnCore/TxnManager.cpp
- iModelCore/iModelPlatform/PublicAPI/DgnPlatform/TxnManager.h
- iModelJsNodeAddon/IModelJsNative.cpp
When there is a readonly connection to the same briefcase as a writeable briefcase, changes are not visible until a call to `restartDefaultTxn`. This PR adds logic to that method to read the new Txns and send the changed element/model events for the readonly connection as if they were made by it.
itwinjs-core: https://github.com/iTwin/itwinjs-core/tree/readonly-briefcases
> Send element/model changed events from readonly briefcases 

- iModelCore/ECPresentation/Source/Hierarchies/NavNodeProviders.cpp
- iModelCore/ECPresentation/Tests/NonPublished/Integration/Hierarchies/Hierarchies_Limiting.cpp
Contains 2 fixes:
1. Performance - we should call `CreateContextForChildHierarchyLevel` with hierarchy level size limit of the parent hierarchy level context. Generally the same limit is used for the whole hierarchy, so this helps us avoid creating 2 copies of the hierarchy level (one with limit, one without).
2. Bug - we were not setting hierarchy level size limit on the merged data source identifier, so merged data sources weren't found when requesting nodes from cache.
> Presentation: Hierarchy level size limiting fixes

- iModelCore/ECPresentation/Source/Hierarchies/NavNodesCache.cpp
- Execute nodes count query with a limit
- Must optimize within a savepoint
> Presentation: Speed up hierarchy cache savepoints

- iModelCore/libsrc/libjpegturbo/BeLibJpegTurbo.mke
- iModelCore/libsrc/libxml2/BeLibxml2.mke
This upgrade allow us to consume relevant configurations of `JpegTurbo` and `LibXml2` components in iTwinNativeThirdParty. The reason of doing this upgrade is that now we want to consume the duplicate/similar components from a central location.
> Configurations to consume JpegTurbo and LibXml2 Components in iTwinNativeThirdParty

- iModelCore/ECPresentation/Source/PresentationManagerImpl.cpp
- iModelCore/ECPresentation/Source/PresentationManagerImpl.h
We just got the parent of specific child node, so we know that the parent has children - no need to determine that.
> Presentation: Avoid determining children for parent node

- iModelCore/ECPresentation/PublicAPI/ECPresentation/ECPresentationManagerRequestParams.h
- iModelCore/ECPresentation/PublicAPI/ECPresentation/NavNode.h
- iModelCore/ECPresentation/Source/ECPresentationManager.cpp
- iModelCore/ECPresentation/Source/Hierarchies/NavNodeProviders.cpp
- iModelCore/ECPresentation/Source/Hierarchies/NavNodeProviders.h
- iModelCore/ECPresentation/Source/Hierarchies/NavNodesCache.h
- iModelCore/ECPresentation/Source/Hierarchies/NodePathsHelper.cpp
- iModelCore/ECPresentation/Source/Hierarchies/NodePathsHelper.h
- iModelCore/ECPresentation/Source/PresentationManagerImpl.cpp
- iModelCore/ECPresentation/Source/PresentationManagerImpl.h
- iModelCore/ECPresentation/Tests/NonPublished/Helpers/StubRulesDrivenECPresentationManagerImpl.h
- iModelCore/ECPresentation/Tests/NonPublished/Helpers/TestRulesDrivenECPresentationManagerImpl.h
- iModelCore/ECPresentation/Tests/NonPublished/Unit/Hierarchies/NodesProviderTests.cpp
Filtered models tree filtering performance on a specific test iModel (17 GB, lots of Subjects & Models, 1281 nodes in filtered hierarchy):
| | 4.0.12 | before this PR | after this PR |
| --- | --- | --- | --- |
| Initial filter | 59.453 s | 47.179 s | 44.385 s |
| Subsequent filters | 3.671 s | 2.277 s | 1.429 s |
Not sure if we can squeeze anything more from this...
itwinjs-core PR: https://github.com/iTwin/itwinjs-core/pull/5767
itwinjs-core: https://github.com/iTwin/itwinjs-core/tree/presentation/update-snapshots-after-filtering-changes
> Presentation: Hierarchy filtering perf. improvements

- iModelCore/ECPresentation/Source/ECPresentationManager.cpp
- iModelCore/ECPresentation/Source/PresentationManagerImpl.cpp
I was pretty sure we have them, but turns out we don't...
Provides ~6-7% performance boost for requests that run large numbers of queries (Models tree initial load & filtering, consolidated content descriptor).
> Presentation: Use request-level read transactions

- iModelCore/ECDb/ECDb/ECSql/ECSqlFieldFactory.cpp
- iModelCore/ECDb/ECDb/ECSql/ECSqlInsertPreparer.cpp
- iModelCore/ECDb/ECDb/ECSql/ECSqlParser.cpp
- iModelCore/ECDb/ECDb/ECSql/ECSqlPreparer.cpp
- iModelCore/ECDb/ECDb/ECSql/JoinExp.cpp
- iModelCore/ECDb/ECDb/ECSql/JoinExp.h
- iModelCore/ECDb/ECDb/ECSql/SelectStatementExp.cpp
- iModelCore/ECDb/ECDb/ECSql/SelectStatementExp.h
- iModelCore/ECDb/ECDb/ECSql/UpdateStatementExp.cpp
- iModelCore/ECDb/ECDb/ECSql/ValueExp.cpp
The clang from the current Xcode generates a warning when std:: prefix is missing from move calls, and warnings are treated as errors. Many (most?) existing calls to move already have the std:: prefix, despite `using namespace std` being present in one of the top-level EC header files.
For reference, the error comes from `-Wunqualified-std-call`. I assume that the bb settings either specify -Wmost and this is in the list for that, or that they specify -Wall. This specific warning could be disabled in bsicommon, but I feel that adding the std:: prefix is better since it is in use in so many other std::move calls. If others disagree, this PR can be closed and bsicommon can be updated to exclude that warning.
> Always use std:: prefix when calling move

- iModelCore/iModelPlatform/DgnCore/SimplifyGraphic.cpp
The offset from the text itself is now taken into account along with the glyph offset.
> fix text offset for SimplifyGraphic::ProcessText

- iModelCore/ECPresentation/Source/Content/ContentProviders.cpp
- iModelCore/ECPresentation/Source/Content/ContentProviders.h
- iModelCore/ECPresentation/Source/Content/ContentQueryBuilder.cpp
- iModelCore/ECPresentation/Source/Content/ContentQueryBuilder.h
- iModelCore/ECPresentation/Tests/NonPublished/Integration/Content/Content_RelatedPropertiesTests.cpp
Fixes https://github.com/iTwin/itwinjs-backlog/issues/846.
1. Related content may have a large number of nested related content fields, causing us to exceed max joins limit. So we have to handle related content similar to how we handle direct content - count related classes and query related content separately if the number of related classes is too large.
2. When counting related classes, we have to add one for every navigation property as they require joining the target class.
> Handle nested content similar to how we handle direct content

- iModelCore/ECPresentation/PublicAPI/ECPresentation/Content.h
- iModelCore/ECPresentation/Tests/NonPublished/Unit/Content/ContentDescriptorTests.cpp
We didn't update child fields' parent pointer after cloning them...
> Presentation: Fix `NestedContentField` copy constructor

- iModelCore/iModelPlatform/DgnCore/FontManager.cpp
TTC data is embedded as a single row in be_Prop, and its metadata describes all the faces in the collection. The intent and comment of FontDb::Load was correct, but you should return false in ForEachArrayMember's callback to continue iterating.
> Patch FontDb::Load to correctly load fonts with many faces

- iModelJsNodeAddon/JsCloudSqlite.cpp
- iModelJsNodeAddon/api_package/ts/src/NativeLibrary.ts
itwinjs-core: https://github.com/iTwin/itwinjs-core/tree/nick/exposebcvkvtime
I noticed that write lock expiry time no longer gets updated when you call acquireWriteLock in TS with the same user. I didn't want to test against the containerInternal object and preferred to have validation from the getter that I'm adding in which reads the actual bcv_kv table.
> make writeLockExpires a getter

- iModelCore/ECDb/CHANGES.md
- iModelCore/ECDb/ECDb/BuiltInFuncs.cpp
- iModelCore/ECDb/ECDb/BuiltInFuncs.h
- iModelCore/ECDb/ECDb/ECSql/ECSqlPreparer.cpp
- iModelCore/ECDb/ECDb/ECSql/ECSqlPreparer.h
- iModelCore/ECDb/ECDb/ECSql/OptionsExp.cpp
- iModelCore/ECDb/ECDb/ECSql/OptionsExp.h
- iModelCore/ECDb/ECDb/QueryJsonAdaptor.cpp
- iModelCore/ECDb/PublicAPI/ECDb/ECDb.h
- iModelCore/ECDb/PublicAPI/ECDb/InstanceReader.h
- iModelCore/ECDb/Tests/NonPublished/ECDbTests.cpp
- iModelCore/ECDb/Tests/NonPublished/InstanceReaderTest.cpp
1. ECSql version updated to `1.2.6.0` -> `1.2.7.0`.
2. Added following `ECSQLOPTIONS` or `OPTIONS`
* `USE_JS_PROP_NAMES` returns json compilable with iTwin.js typescript.
* `DO_NOT_TRUNCATE_BLOB` return full blob instead of truncating it.
3. Instance access now add `json()` around `extract_inst()` function.
Following return iTwin.js compilable json
```sql
SELECT $ FROM Bis.Element OPTIONS USE_JS_PROP_NAMES
```
Following return complete blob as base64
```sql
SELECT $ FROM  Bis.GeometricElement3d OPTIONS DO_NOT_TRUNCATE_BLOB
```
itwinjs-core: https://github.com/iTwin/itwinjs-core/tree/rohitptnkr/use-instance-queries-getAspects
> Allow customize instance json using OPTIONS flag

- iModelCore/BeSQLite/SQLite/UpdateSqlite.bat
- iModelCore/BeSQLite/SQLite/shell.c
- iModelCore/BeSQLite/SQLite/sqlite3.h
Updated from [itwin-sqlite-v3.43.1-r0](https://github.com/iTwin/sqlite/releases/tag/itwin-sqlite-v3.43.1-r0)
1.  Fix a regression in the way that the [sum()](https://www.sqlite.org/lang_aggfunc.html#sumunc), [avg()](https://www.sqlite.org/lang_aggfunc.html#avg), and [total()](https://www.sqlite.org/lang_aggfunc.html#sumunc) aggregate functions handle infinities.
2.  Fix a bug in the [json\_array\_length()](https://www.sqlite.org/json1.html#jarraylen) function that occurs when the argument comes directly from [json\_remove()](https://www.sqlite.org/json1.html#jrm).
3.  Fix the omit-unused-subquery-columns optimization (introduced in in version 3.42.0) so that it works correctly if the subquery is a compound where one arm is DISTINCT and the other is not.
4.  Other minor fixes.
1.  Add …
> Update SQLite to v3.43.1

- .vscode/launch.json
- iModelCore/iModelPlatform/DgnCore/RenderMaterial.cpp
`getDPoint2d` asserts the requested property must exist, but constant LOD params offset is optional.
imodel-native-internal: https://github.com/iTwin/imodel-native-internal/pull/175
> Silence spurious assertion

- iModelCore/GeomLibs/PublicAPI/Geom/AnalyticRoots.h
It lists the `uvals` array as being of size 2 when the C++ file lists (and requires) 3. The incorrect code causes a compile error in Xcode 15.
> Fix typo in SolveBezierCubic declaration

- iModelCore/libsrc/facebook/VendorApi/folly/Range.h
It contains code that uses `unsigned char` in a `char_traits`, which produces a compile error in Xcode 15 due to the behavior being undefined. Since the functionality isn't used, wrap it in an ifdef to disable it entirely.
> Disable broken unused functionality in folly

- iModelCore/ecobjects/PublicApi/ECObjects/ECContext.h
- iModelCore/ecobjects/PublicApi/ECObjects/ECSchema.h
- iModelCore/ecobjects/src/ECCustomAttribute.cpp
- iModelCore/ecobjects/src/ECSchema.cpp
- iModelCore/ecobjects/src/ECcontext.cpp
- iModelCore/ecobjects/src/SchemaXml.cpp
- iModelCore/ecobjects/test/NonPublished/AdhocPropertyTests.cpp
- iModelCore/ecobjects/test/NonPublished/CopyTests/ClassCopyTests.cpp
- iModelCore/ecobjects/test/NonPublished/ECSchemaValidatorTests.cpp
- iModelCore/ecobjects/test/NonPublished/SchemaDeserializationTests.cpp
- iModelCore/ecobjects/test/NonPublished/SchemaTests.cpp
Previously, the CA deserialization would go through the schema read context and may occasionally obtain a wrong (compatible) schema version which would then be used to load the CA and be added as a reference to the schema in which the CA is in.
The deserializer now prioritizes the container schema and its references when locating schemas used for custom attributes. Also added a defensive check to make sure schemas never reference another schema of the same name.
> Fix CA loading when schema context has multiple versions of same schema

- iModelCore/iModelPlatform/PublicAPI/DgnPlatform/ElementGeometry.h
imodel-native-internal: https://github.com/iTwin/imodel-native-internal/pull/181
> Export method to read IBRepEntity from geometry stream

- iModelCore/iModelPlatform/DgnCore/linestyle/DgnLineStyles.cpp
- iModelCore/iModelPlatform/DgnCore/linestyle/LsDb.cpp
- iModelCore/iModelPlatform/DgnCore/linestyle/LsSymbology.cpp
- iModelCore/iModelPlatform/DgnCore/linestyle/StrokeSymbol.cpp
- iModelCore/iModelPlatform/PublicAPI/DgnPlatform/LineStyle.h
Partial fix for [issue](https://github.com/iTwin/itwinjs-core/issues/6010#event-10498971483l) also need change to batch connector.
itwinjs-core: https://github.com/iTwin/itwinjs-core/pull/6039
Previously padding only considered width of line style definition without considering modifiers which can both increase or decrease the overall width. There was a special case for continuous with width, but this did not account for point symbol or stroke pattern width.
This also fixes keeping the line style name map up to date when new styles are inserted. This previously was done in the C++ method and has now been move to the _OnInsert method of the line style definition element.
> Fix to line style max offset calculation to properly account for modifiers.

- iModelJsNodeAddon/JsInteropDgnDb.cpp
Reverts #478.
Until now the addon didn't support run-time type information on Apple builds, so polymorphic exceptions didn't work and required a workaround. Now that RTTI has been added, these workarounds are no longer necessary.
> Revert polymorphic exception workaround

- iModelCore/ECDb/Tests/NonPublished/ECDbTests.cpp
Test was copied from another test which sometimes causes file lock issues when creating the DB
> Fixed ECDb name for test which caused flaky build

- iModelCore/BeSQLite/ChangeSet.cpp
- iModelCore/BeSQLite/PublicAPI/BeSQLite/ChangeSet.h
- iModelCore/BeSQLite/SQLite/UpdateSqlite.bat
- iModelCore/BeSQLite/SQLite/shell.c
- iModelCore/BeSQLite/SQLite/sqlite3.h
- iModelCore/BeSQLite/Tests/NonPublished/BeSQLiteDb_Test.cpp
- iModelCore/iModelPlatform/DgnCore/ChangesetTxns.cpp
- iModelCore/iModelPlatform/Tests/DgnProject/NonPublished/RevisionMem_Test.cpp
* [Fix a problem with sqlite3changegroup_schema() and patchsets.](https://github.com/iTwin/sqlite/commit/3b381b4afccd90e1c2cdd5cd5ea3ba9f15ba358b) 
* [Add the sqlite3changegroup_schema() API. To allow changegroup objects…](https://github.com/iTwin/sqlite/commit/4bdcfc6666a99a9710cb94541afadf49e84bf2bc)
* [Fix a problem with the changes on this branch and tables that use an …](https://github.com/iTwin/sqlite/commit/18efe17553c8c777452607d6605cf77a00142418)
* [Add missing source code comments and fix other issues with the new co…](https://github.com/iTwin/sqlite/commit/83e43dc757d0572dc468129f08f6a1e54d917f43)
* [Add tests for the sqlite3changegroup_schema() API.](https://github.com/iTwin/sqlite/commit/53e91a5e22172d57edc095dd89c85524860815f5)
* [Add the sqlite3changegroup_schema() API. To …
> Update SQLite to 3.43.2 + cherry-picked changeset grouping enhancement

- iModelCore/BeSQLite/SQLite/blockcachevfsd.c
Part of what I posted on CloudSQLite forum (Excluding logs and callstack):
My interpretation of what took place is that a client triggered a prefetch and during that prefetch the client was forcefully shutdown(unrelated to anything CloudSQLite). Daemon calls bdDisconnectClient without issue during the forceful shutdown. A block finishes downloading so the daemon goes to reply, it gets a send() failure and tries to call bdDisconnectClient again. I guess the daemon does not think the send() failure occurred due to potentially already being disconnected?
Reply from CloudSQLite team: 
"Thanks for looking into this. I think your analysis is correct. The bug has already happened by the time send() is called though - we can't depend on a closed file-descriptor being invalid as unix systems tend …
> CloudSQLite: Fix daemon segfault when client disconnects during prefetch

- iModelCore/iModelPlatform/Tests/DgnProject/Compatibility/CompatibilityRunner/PrepareCurrentTestRunner.mke
- iModelCore/iModelPlatform/Tests/DgnProject/Compatibility/CompatibilityRunner/PreparePulledTestRunners.mke
- iModelCore/iModelPlatform/Tests/DgnProject/Compatibility/CompatibilityRunner/PrepareTestFilesNugetPackaging.mke
- iModelCore/iModelPlatform/Tests/DgnProject/Compatibility/CompatibilityRunner/PullNugets.mke
- iModelCore/iModelPlatform/Tests/DgnProject/Compatibility/CompatibilityRunner/RunPulledTestRunners.mke
After the recent changes to `strategy.py`, the build has started failing with the following error:
```
python Tests\DgnProject\Compatibility\CompatibilityRunner\PullNugets.py D:\vsts_a\49\bbsrc\\nuget\iModelEvolutionTests\ D:\vsts_a\49\b\Winx64\iModelEvolutionTests D:\vsts_a\49\b\Winx64\iModelEvolutionTests\Nugets D:\vsts_a\49\bbsrc\BentleyBuild\bentleybuild
Traceback (most recent call last):
File "Tests\DgnProject\Compatibility\CompatibilityRunner\PullNugets.py", line 13, in <module>
from bblib import globalvars, nugetpkg, strategy, symlinks
File "D:\vsts_a\49\bbsrc\bentleybuild\bblib\strategy.py", line 2005
def AddEnvIfNotThere (envVar: str, value: str):
^
SyntaxError: invalid syntax
BBMake: call trace
line:   24, D:\vsts_a\49\bbsrc\imodel-native\iModelCore\iModelPlatform\Tests\DgnProjec …
```
> Fix for import issue while building the iModel Evolution Tests

- iModelCore/iModelPlatform/Tests/DgnProject/Compatibility/IModelCompatibilityTests.cpp
To delete KoQs, we need to use the Custom Attribute "AllowUnitChange" which is in the schema "SchemaUpgradeCustomAttributes.1.0.0".
The schema "SchemaUpgradeCustomAttributes.1.0.0" is ECXML 3.2 which is not supported by profile version 4.0.0.1, which is what caused the evolution tests to fail for the 4.0.0.1 profile version test files.
I've split out the KoQ deletion into a separate test case which skips over the 4.0.0.1 test files.
> Fix evolution test failure due to 4.0.0.1 test files

- iModelJsNodeAddon/IModelJsNative.cpp
Was getting a [crash](https://bentley-systems-inc.sentry.io/issues/4660238515/events/b0fc6d3c977441d5b4ce990b5949d72c/?project=1520306) from this in tests of my application. This will now throw a javascript error about an invalid/closed db instead of dereferencing a null pointer.
Since `RequireDbIsOpen` is called by most users of `_GetMyDb` (e.g. `GetOpenedDb`), I expect this to be a sufficient change. We could however also change more code and always check for nullness of the result of `_GetMyDb` before using it. Or consider something else.
> check that db is not null before checking if it's open in RequireDbIsOpen

- iModelJsNodeAddon/IModelJsNative.cpp
- iModelJsNodeAddon/api_package/ts/src/NativeLibrary.ts
- iModelJsNodeAddon/api_package/ts/src/test/DgnDb.test.ts
- iModelJsNodeAddon/api_package/ts/src/test/ECDb.test.ts
- iModelJsNodeAddon/api_package/ts/src/test/EmbedFont.test.ts
- iModelJsNodeAddon/api_package/ts/src/test/EmbeddedFile.test.ts
- iModelJsNodeAddon/api_package/ts/src/test/SqlStatement.test.ts
- iModelJsNodeAddon/api_package/ts/src/test/importSchema.test.ts
This pull request introduces changes to the iModel closing mechanism. Now, closing an iModel file no longer automatically saves changes. Users must explicitly call the `saveChanges` function before closing the iModel. Additionally, the `closeIModel` API has been renamed to `closeFile` for improved clarity.
itwinjs-core: https://github.com/iTwin/itwinjs-core/pull/6232
> Remove automatic save changes on closing DgnDb

- iModelCore/BeSQLite/CloudSqlite.cpp
- iModelJsNodeAddon/JsLogger.cpp
On mobile devices where backend logging is configured to forward to the frontend, doing a JS log too early in the startup process results in an unhandled exception due to the fact that the frontend and backend are not yet connected. Catch that exception when it happens and store the failed log message in the list of deferred log messages. Also process the list of deferred log messages any time IsSeverityEnabled is called so that you don't have to wait for an enabled severity message to be logged before the deferred ones get processed.
> Fix JS logging leading to a crash on mobile

- iModelCore/BeSQLite/CloudSqlite.cpp
The old code worked, but generated a warning message about a COMMIT with no open transaction. The new code is based on recommendations from Keith Bentley.
> Fix GUID db generation code

- iModelCore/ecobjects/src/ECCustomAttribute.cpp
- iModelCore/ecobjects/src/ECcontext.cpp
- iModelCore/ecobjects/test/NonPublished/SchemaDeserializationTests.cpp
- iModelCore/ecobjects/test/Performance/PerformanceSchemaDeserializationTests.cpp
This pull request addresses a performance bottleneck in schema loading. The code now checks if a schema, defining custom attributes, is in the pruned schemas list before attempting to locate them.
> Optimize schema load performance having CustomAttribute from pruned schemas

- iModelCore/ECDb/ECDb/RemapManager.cpp
- iModelCore/iModelPlatform/DgnCore/DgnDbSchema.cpp
- iModelCore/iModelPlatform/Tests/DgnProject/NonPublished/SchemaRemap_Test.cpp
Fixes https://github.com/iTwin/itwinjs-backlog/issues/1007.
Added AllowDataTransformDuringSchemaUpgrade schema import option to the legacy v8 import logic.
> Allow data transform in legacy v8 imports

- iModelCore/ECPresentation/Source/Content/ContentItemBuilder.cpp
- iModelCore/ECPresentation/Source/Content/ContentItemBuilder.h
- iModelCore/ECPresentation/Source/Content/ContentProviders.cpp
- iModelCore/ECPresentation/Tests/NonPublished/Integration/Content/ContentIntegrationTests.cpp
- iModelCore/ECPresentation/Tests/NonPublished/Integration/Content/Content_RelatedPropertiesTests.cpp
Fixes https://github.com/iTwin/imodel-native/issues/586.
Fixes a regression caused by https://github.com/iTwin/imodel-native/pull/582. 
The values were not detected as being different if one one of them was `null` and the other - not. The null value didn't get into the values map (an optimization made in the mentioned pr), then when handling the non-null value we didn't know anything about an already handled value and whether it's different from the current one.
> Presentation: Fix merging null content values

- iModelCore/BeSQLite/SQLite/UpdateSqlite.bat
- iModelCore/BeSQLite/SQLite/shell.c
- iModelCore/BeSQLite/SQLite/sqlite3.h
- iModelCore/BeSQLite/SqliteLib.mke
- iModelCore/BeSQLite/SqliteShell.mke
1.  Added the [SQLITE\_RESULT\_SUBTYPE](https://www.sqlite.org/c3ref/c_deterministic.html#sqliteresultsubtype) property for [application-defined SQL functions](https://www.sqlite.org/appfunc.html). All application defined SQL functions that invokes [sqlite3\_result\_subtype()](https://www.sqlite.org/c3ref/result_subtype.html) must be registered with this new property. Failure to do so might cause the call to sqlite3\_result\_subtype() to behave as a no-op. Compile with [\-DSQLITE\_STRICT\_SUBTYPE=1](https://www.sqlite.org/compile.html#strict_subtype) to cause an SQL error to be raised if a function that is not [SQLITE\_RESULT\_SUBTYPE](https://www.sqlite.org/c3ref/c_deterministic.html#sqliteresultsubtype) tries invokes [sqlite3\_result\_subtype()](https://www.sqlite.org/c3ref/result_subtyp …
> Update SQLite to 3.45

- iModelCore/ECPresentation/Source/Content/ContentItemBuilder.cpp
- iModelCore/ECPresentation/Source/Content/ContentQueryResultsReader.cpp
- iModelCore/ECPresentation/Tests/NonPublished/Integration/Content/ContentIntegrationTests.cpp
Fixes https://github.com/iTwin/imodel-native/issues/586.
This is a follow-up of https://github.com/iTwin/imodel-native/pull/587, which didn't fully fix the problem, because it didn't handle the situation when fields with properties of different classes are being merged.
> Presentation: Fix property value merging for properties of different classes

- iModelCore/ECDb/ECDb/ConcurrentQueryManagerImpl.cpp
The crash is caused by close primary connection by the time cache connection is closed. The fix is to not attempt to remove sql functions as they already deleted when primary connection was closed.
[Sentry.io crash](https://bentley-systems-inc.sentry.io/issues/4887884042/?alert_rule_id=9206371&alert_timestamp=1705584695496&alert_type=email&notification_uuid=a6c12c4f-03cb-4b14-8ccd-363d900f10c3&project=1520306&referrer=alert_email) `EXCEPTION_ACCESS_VIOLATION_READ / 0x254d0e38928`
> Fix crash when closing cached connection try to remove sql functions

- iModelCore/GeomLibs/PublicAPI/Geom/Polyface.h
- iModelCore/GeomLibs/PublicAPI/Geom/rotmatrix.h
- iModelCore/GeomLibs/geom/src/bspline/bspmisc.cpp
- iModelCore/GeomLibs/geom/src/polyface/PolyfaceQuery.cpp
- iModelCore/GeomLibs/geom/src/polyface/pf_purgeDuplicates.cpp
- iModelCore/GeomLibs/geom/src/structs/cpp/refmethods/refrotmatrix.cpp
- iModelCore/GeomLibs/geom/test/PolyfaceTest/t_polyface.cpp
- iModelCore/GeomLibs/geom/test/structsTest/t_RotMatrix.cpp
Backport from imodel02.
Add new methods needed by connectors:
* `RotMatrix::IsRigidSignedScale`: new overload that takes a tolerance
* `PolyfaceQuery::IsFacetOrientationConsistent`: count matching interior edges to determine if a face loop is reversed
* `PolyfaceHeader::CloneWithConsistentlyOrientedFacets`: create a new mesh with face loops consistently oriented
Also:
*  `mdlBspline_validateCurveKnots`: validate weights even when recomputing knots.
* `RotMatrix::IsRigidScale`: use more accurate test for detecting uniform scales when they are tiny.
> [backport] Polyface and RotMatrix fixes

- iModelCore/ECPresentation/Source/Content/ContentProviders.cpp
- iModelCore/ECPresentation/Tests/NonPublished/Integration/Content/ContentIntegrationTests.cpp
Fixes https://github.com/iTwin/imodel-native/issues/565
> Presentation: Fix invalid content set size being returned for non-existing elements when merging results

- iModelCore/ECPresentation/Source/Connection.cpp
We have a situation where content is being requested for a large set of elements and the number of related classes is > 100. This means that getting properties for an element includes running > 100 smaller queries to get related properties. The statement cache was too small to accommodate all these queries and we were spending a lot of time re-preparing them. Increased the cache size...
> Presentation: Increase statement cache size

- iModelCore/BeSQLite/SQLite/blockcachevfs.c
https://sqlite.org/cloudsqlite/forumpost/7c554f886d
"Hi Nick,
I think it's compiling with -DSQLITE_DIRECT_OVERFLOW_READ that is exposing the bug. Should now be fixed here:
https://sqlite.org/cloudsqlite/info/f6145230ca6bf01882ca
Thanks,
Dan."
> CloudSQLite update: Fixes so that things work with SQLITE_DIRECT_OVERFLOW_READ.

- iModelCore/ECPresentation/Source/Hierarchies/NavNodesCache.cpp
- iModelCore/ECPresentation/Source/Hierarchies/NavNodesCacheHelpers.h
- iModelCore/ECPresentation/Tests/NonPublished/Integration/Hierarchies/Hierarchies_Limiting.cpp
Fixes https://github.com/iTwin/imodel-native/issues/620.
In addition, there was a problem that same-label grouping nodes were returned in wrong order when requesting in pages.
> Presentation: Fix nodes getting duplicated when using hierarchy level limiting with same label instance grouping under hidden nodes

- iModelCore/ECPresentation/PublicAPI/ECPresentation/Content.h
- iModelCore/ECPresentation/Source/Content/ContentDescriptorBuilder.cpp
- iModelCore/ECPresentation/Tests/NonPublished/Integration/Content/Content_DistinctValuesTests.cpp
Fixes https://github.com/iTwin/imodel-native/issues/622
Related distinct values were not being picked up when polymorphically selecting properties and related properties spec has `skipIfDuplicate = true`.
> Presentation: Fix related distinct values not being picked up in specific cases

- iModelCore/GeomLibs/PublicAPI/Geom/MSBsplineCurve.h
- iModelCore/GeomLibs/geom/src/CurvePrimitive/CurvePrimitiveBsplineCurve.cpp
- iModelCore/GeomLibs/geom/src/bspline/bsputil.cpp
- iModelCore/GeomLibs/geom/test/CurvePrimitiveTest/t_IGeometry.cpp
Hopefully resolves https://github.com/iTwin/imodel-native-internal/issues/388 with paranoid validation.
Without a test case to reproduce this Sentry crash, we don't know how this corrupt B-spline curve is creeping into tile generation.
> Try to fix Sentry crash on bad B-spline curve [buildNum:2024.02.21.18]

- build/begin_addon_release.yml
GH token was needed for testing, but in this context it is not necessary since we don't need to use the GH apis. If we decided to open a PR description or comments then it would be needed again.
> Remove GH token in begin release pipeline [buildNum:2024.02.22.13]

- iModelCore/Bentley/PublicAPI/Bentley/WString.h
A compilation error showed up when using VS2022 in debug mode.
(note that it was working fine with VS2019)
I believe that we already encountered this error in that past:
```
template<typename... Args> static int Sscanf_safe(const char* const buffer, const char* const format, Args&&... args) {
// NOTE: When we use C++17 this can be string_view and become a static_assert
// The lambda is because of a compiler error with just the straight expression. It does not seem to like the temporary variable in the template.
BeAssert([](const char* const format) {return (std::string::npos == std::string(format).find("%s") && "%s is unsafe, do not use sscanf for that purpose");}(format));
// ...
}
```
The error is a bit obscure, and seems to occur when calling std::string.find() inside a template …
> Fix compiler error with VS2022/Debug

- iModelCore/iModelPlatform/Tests/DgnProject/Compatibility/TestIModelCreators.cpp
Consume `Bentley_Standard_CustomAttributes` schema version `01.14` which is the latest released version.
> Fixed iModel Evolution Tests

- build/begin_addon_release.yml
Always build when a commit goes into main, even if there is a linked PR. The imodel-native-internal commit will skip over the release instead
imodel-native-internal: https://github.com/iTwin/imodel-native-internal/pull/419
> remove no ci logic

- iModelJsNodeAddon/api_package/ts/package-lock.json
- iModelJsNodeAddon/api_package/ts/package.json
- iModelJsNodeAddon/api_package/ts/src/test/index.ts
Closes https://github.com/iTwin/imodel-native/issues/649
> Bump `itwinjs-core` dependency version and clean up logging workaround

- iModelCore/ECPresentation/Source/ECPresentation.vcxproj
- iModelCore/ECPresentation/Source/ECPresentation.vcxproj.filters
- iModelCore/ECPresentation/Source/Hierarchies/HierarchiesFiltering.cpp
- iModelCore/ECPresentation/Source/Hierarchies/NavNodesHelper.cpp
- iModelCore/ECPresentation/Source/Shared/Queries/PresentationQuery.cpp
- iModelCore/ECPresentation/Tests/NonPublished/Integration/Hierarchies/Hierarchies_InstanceFiltering.cpp
Fixes https://github.com/iTwin/imodel-native/issues/669.
Found & fixed two problems:
1. We have 2 specifications that return child Subjects - one that returns hidden nodes and one that returns visible ones. When traversing through the hidden nodes spec, we find the same two specifications for children level. Those specs are visited and added to visited specs list, but don't contribute to the resulting descriptor. Then, when visiting the specification that contributes to the resulting descriptor, we find it in the visited specs list and don't process it. This was causing Subject class to not be included in the descriptor.
2. The specification that loads Model nodes uses a `parent` ECExpression symbol to join itself to the parent Subject. However, if the parent Subjects level is hidden, we …
> Presentation: Fix creating hierarchy level descriptor in specific cases

- iModelJsNodeAddon/IModelJsNative.cpp
Fixes https://github.com/iTwin/itwinjs-core/issues/6517. See that issue for details.
Basically, when you close a NativeDgnDb it nulls out `m_dgndb`. Every method that needs a non-null `DgnDbPtr` **must** verify that condition, to avert a segmentation fault. Every method that requires an open or writable db should verify that.
itwinjs-core: https://github.com/iTwin/itwinjs-core/pull/6534
> Enforce preconditions in NativeDgnDb methods

- iModelCore/ECDb/ECDb/SchemaManager.cpp
- iModelCore/ECDb/Tests/NonPublished/SchemaUpgradeTests.cpp
Dropping a very large number of schemas takes a very long time. With a specific iModel dropping `922` schemas takes 1 hour and 25 minutes. 
Most of the time is spent trying to figure out if the schema has an instance or has FK references.
To improve performance the check now limits the instance search to specific schema classes previously it used root relationships and classes to search for instances. This causes unrelated relationships to be searched for schema classes that are going to be dropped. 
This improvement for the given data set brings overall time to 15 min from over an hour.
> Improve performance of drop schema

- iModelCore/ECPresentation/PublicAPI/ECPresentation/ECPresentationManager.h
- iModelCore/ECPresentation/PublicAPI/ECPresentation/ECPresentationTypes.h
- iModelCore/ECPresentation/Source/PresentationManagerImpl.cpp
- iModelCore/ECPresentation/Source/PresentationManagerImpl.h
- iModelCore/ECPresentation/Tests/NonPublished/Helpers/RulesDrivenECPresentationManagerImplBase.h
- iModelCore/ECPresentation/Tests/NonPublished/Integration/Content/ContentIntegrationTests.cpp
- iModelCore/ECPresentation/Tests/NonPublished/Integration/Content/Content_DistinctValuesTests.cpp
- iModelCore/ECPresentation/Tests/NonPublished/Integration/Content/Content_PropertyCategorizationTests.cpp
- iModelCore/ECPresentation/Tests/NonPublished/Integration/PresentationManagerIntegrationTests.cpp
- iModelCore/ECPresentation/Tests/NonPublished/Integration/PresentationManagerIntegrationTests.h
- iModelCore/ECPresentation/Tests/NonPublished/Unit/PresentationManagerImplCancelationTests.cpp
- iModelCore/ECPresentation/Tests/NonPublished/Unit/PresentationManagerImplTests.cpp
- iModelCore/ECPresentation/Tests/TestHelpers/PresentationRulesetTest.cpp
- iModelCore/ECPresentation/Tests/TestHelpers/PresentationRulesetTest.h
- iModelJsNodeAddon/IModelJsNative.cpp
- iModelJsNodeAddon/presentation/ECPresentationUtils.cpp
- iModelJsNodeAddon/presentation/ECPresentationUtils.h
`NativeECPresentationManager` was leaking `DefaultPropertyFormatter` instance - `ECPresentationManager` was taking a raw pointer with the intention that its creator would own the property formatter, however `NativeECPresentationManager` never deleted the object. 
While this was the only leak I found, I went ahead and changed a number of other raw pointers to smart ones, making such mistakes harder to do in the future.
> Presentation: Fix a memory leak

- iModelCore/GeomLibs/PublicAPI/GeomSerialization/GeomLibsFlatBufferApi.h
- iModelCore/GeomLibs/geom/test/CurvePrimitiveTest/t_IGeometry.cpp
- iModelCore/GeomLibs/geom/test/SerializationTest/t_imodeljson.cpp
- iModelCore/GeomLibs/serialization/src/FlatBuffer/FixedStructs.cpp
This is done to make names consistent over all repos (imodel-native, imodel02, and PPBase)
> Renamed BytesToVectorOfGeometry to BytesToVectorOfGeometrySafe

- iModelCore/BeGTest/Android/project/app/build.gradle
This is hopefully a fix for https://github.com/iTwin/itwinjs-backlog/issues/1090
> Update BeGTest to compile with Android SDK 31

- iModelCore/ECDb/ECDb/ProfileUpgrader.cpp
Was an oversight during the recent version increment.
> Fix default ECDb schema version numbers for profile 4005

- iModelCore/BeGTest/Android/project/build.gradle
Updates to Android SDK and Gradle on the CI machines require this change.
> Update gradle plugin version to work with new gradle

- iModelCore/iModelPlatform/DgnCore/ElementGeometry.cpp
Fixes clipping at the extremes of rotated text as noted [here](https://github.com/iTwin/itwinjs-core/pull/6693).
It needs to expand the box to fully encompass the rotated box.
> Fix rotated TextString bounding box

- iModelCore/ECPresentation/Source/Shared/RelatedClass.cpp
- iModelCore/ECPresentation/Tests/NonPublished/Integration/Content/Content_RelatedPropertiesTests.cpp
Fix duplicated related property fields when input contains multiple classes and related property spec has an instance filter. This fixes https://github.com/iTwin/viewer-components-react/issues/936.
> Presentation: Fix duplicated related property fields 

- iModelJsNodeAddon/api_package/ts/src/NativeLibrary.ts
itwinjs-core: https://github.com/iTwin/itwinjs-core/pull/6828
NativeLibrary.ts should really just import `Logger` from core-bentley and export `type NativeLogger = Pick<Logger, "categoryFilter" | "etc...">`.
But it can't do that until the updated core-bentley package in linked PR is merged.
I don't know why only the docs build complained about the type discrepancy in the linked PR.
> NativeLogger.categoryFilter is a read-only object

- iModelCore/BeSQLite/SQLite/bentley-sqlite.c
For experiment with full db free text search.
https://github.com/iTwin/itwin-cli/pull/64
```sql
select * from ftsElements where ftsElements MATCH 'Cast Iron AND PaletteName: Metals'
```
**Why FTS4 and not FTS5?**
FTS4 can have very large number of columns. Since it does not store them as column rather just document. FTS5 has arbitrary limit as it store each column as row in table.
> Enable FTS4

- iModelCore/ECDb/Tests/NonPublished/SchemaSyncTest.cpp
- iModelCore/ecobjects/src/ECProperty.cpp
- iModelCore/ecobjects/test/NonPublished/PropertyTests.cpp
Fixes https://github.com/iTwin/itwinjs-backlog/issues/955
itwinjs-core: https://github.com/iTwin/itwinjs-core/pull/7047
> ECSchema deserialization should not fail due to invalid PropertyCategory

- iModelCore/Bentley/PublicAPI/Bentley/BeEvent.h
- iModelCore/libsrc/facebook/VendorApi/folly/BeFolly.h
- iModelJsNodeAddon/JsCloudSqlite.cpp
New warning treated as error: implicit this in lambda capture. Update `[=]` to `[=, this]` where `this` is captured.
Note: I believe that these changes require C++20, but as far as I can tell, all of the code that I modified is set to C++20 mode.
> Fix for Xcode 16 compilation

- iModelJsNodeAddon/api_package/ts/package-lock.json
- iModelJsNodeAddon/api_package/ts/package.json
- iModelJsNodeAddon/api_package/ts/src/NativeLibrary.ts
- iModelJsNodeAddon/api_package/ts/src/test/DgnDb.test.ts
https://github.com/iTwin/itwinjs-core/pull/6828 removed internal `StatusCodeWithMessage` interface, which was being used in addon declarations in a number of places. For consumers this resulted in the following error:
```
../common/temp/node_modules/.pnpm/@bentley+imodeljs-native@4.9.31/node_modules/@bentley/imodeljs-native/NativeLibrary.d.ts(7,132): error TS2305: Module '"../../../../../../../../platform/node_modules/@itwin/core-bentley/lib/cjs/core-bentley"' has no exported member 'StatusCodeWithMessage'.
```
Here I just add the same type of interface to the addon itself.
This reveals that our native addon package setup is flawed - it has no real dependencies on `core-bentley`, `core-common`, etc., but is using their types, relying on `core-backend` delivering those dependencies. This …
> Fix addon declarations

- iModelCore/BeSQLite/PublicAPI/BeSQLite/CloudSqlite.h
I suppose the use of unique_ptr in mark's PR is flagging errors like the below:
"\x1b[1m/usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/unique_ptr.h:85:2: \x1b[0m\x1b[0;1;31merror: \x1b[0m\x1b[1mdelete called on non-final 'BentleyM0200::BeSQLite::CloudContainer' that has virtual functions but non-virtual destructor [-Werror,-Wdelete-non-abstract-non-virtual-dtor]\x1b[0m" 
b"\x1b[1m/usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/unique_ptr.h:361:4: \x1b[0m\x1b[0;1;30mnote: \x1b[0min instantiation of member function 'std::default_deleteBentleyM0200::BeSQLite::CloudContainer::operator()' requested here\x1b[0m" 
b"\x1b[1m/home/GeoCoord.cpp:26:11: \x1b[0m\x1b[0;1;30mnote: \x1b[0min instantiation of member function …
> mark cloud container destructor virtual

- iModelJsNodeAddon/api_package/ts/src/test/EmbedFont.test.ts
A followup PR will reenable these tests so that we can track down the root cause and fix it.
> Temp disable two font tests that are failing on Mac CI machines

- iModelCore/ECDb/ECDb/SchemaSync.cpp
- iModelCore/ECDb/ECDb/SchemaSync.h
- iModelCore/ECDb/Tests/NonPublished/SchemaSyncTest.cpp
Cache table were found to be out of date after apply changeset. Schema sync now recompute cache table on pull and apply changeset. 
Beside above removed a unused function `SchemaSyncHelper::CreateMetaTablesFrom()`
Issue found in connector on imodel02
> Update ec cache tables after schema changeset apply and schema sync pull

- iModelJsNodeAddon/api_package/ts/src/NativeLibrary.ts
itwinjs-core: https://github.com/iTwin/itwinjs-core/pull/7512
The implementation treats `forceUseId` as optional but TS API claims it's required. Make it optional.
simplifyElementGeometry returns DgnDbStatus aka IModelStatus, not DbResult.
> Fix NativeLibrary types

- iModelCore/ECPresentation/Source/Hierarchies/NavigationQueryBuilder.cpp
- iModelCore/ECPresentation/Source/UpdateHandler.cpp
- iModelCore/ECPresentation/Tests/NonPublished/Helpers/TestHelpers.cpp
- iModelCore/ECPresentation/Tests/NonPublished/Integration/Hierarchies/HierarchyIntegrationTests.cpp
When a hierarchy specification selects from two base classes of the same instance (e.g. through the use of a mixin), `groupedInstancesCount` of class grouping nodes was being duplicated.
1. Improved hierarchies validation in tests to compare expected instances' count with the actual count set on grouping nodes.
2. Fixed navigation query builder to filter-out duplicate select classes, when the duplication happens due to class grouping.
3. Tests' improvement detected a bug in hierarchies update, where we weren't updating grouping nodes after deleting grouped instances. Fixed that as well.
> Presentation: Fix incorrect class grouping nodes' grouped instances count

- iModelCore/libsrc/openssl/vendor/crypto/x509/by_dir.c
The patch was intended to fix Android certificate lookup, but an uninitialized variable would sometimes lead to a crash.
> Fix uninitialized variable in Android-only OpenSSL patch

- iModelCore/iModelPlatform/DgnCore/DgnElement.cpp
- iModelCore/iModelPlatform/Tests/DgnProject/NonPublished/ElementAspect_Test.cpp
Issue Link: https://github.com/iTwin/itwinjs-backlog/issues/1355
Added test case to check whether if we can import elements with unique aspect, successfully.
The fix now enables us to do just that.
> Fix for DgnElement::Aspect::ImportAspects 

- iModelCore/GeomLibs/PublicAPI/Geom/capi/dray3d_capi.h
- iModelCore/GeomLibs/geom/src/structs/dray3d.cpp
- iModelCore/GeomLibs/geom/test/structsTest/t_DRay3d.cpp
Ray3d.intersectionWithTriangle was not finding intersection of a Ray3d into a triangle if ray origin was on the triangle.
> Fixed Ray3d flaky test

- iModelCore/ECDb/ECDb/ECSqlRowAdaptor.cpp
Returns an Empty Object when a null value is passed in to RenderStructArrayProperty. This ensures that https://github.com/iTwin/itwinjs-core/pull/6549 will maintain current functionality. 
Related Issue: https://github.com/iTwin/itwinjs-backlog/issues/1162
> Return Empty Object for Null Struct Array Values

- iModelCore/libsrc/flatbuffers/source/include/flatbuffers/flatbuffers.h
Fix [FlatBuffer 1.12.0](https://github.com/iTwin/imodel-native/pull/1009) [compilation for clang-19](https://github.com/iTwin/imodel-native/pull/1009#issuecomment-2684859454) with deleting TableKeyComparator operator referred to other deleted ones:
> /home/rob/code/imodel-native/out/LinuxX64/static/BuildContexts/geomlibs/VendorAPI/flatbuffers/flatbuffers.h:1881:12: error: overload resolution selected deleted operator '='
/home/rob/code/imodel-native/out/LinuxX64/static/BuildContexts/geomlibs/VendorAPI/flatbuffers/flatbuffers.h:1004:44: note: candidate function has been explicitly deleted'
/home/rob/code/imodel-native/out/LinuxX64/static/BuildContexts/geomlibs/VendorAPI/flatbuffers/flatbuffers.h:836:20: note: candidate function not viable: expects an rvalue for 1st argument'
> Fix FlatBuffers 1.12.0 compilation for clang-19

- iModelCore/iModelPlatform/DgnCore/SnapContext.cpp
Fixes https://github.com/iTwin/imodel-native-internal/issues/759
Crash happens on snapping to a closed B-spline surface, but as this comes from Sentry, we don't know anything else about the element. This fix just avoids the crash.
> Avoid null deref when snapping to B-spline surface 

- iModelCore/iModelPlatform/DgnCore/TxnManager.cpp
- iModelCore/iModelPlatform/PublicAPI/DgnPlatform/TxnManager.h
- iModelJsNodeAddon/presentation/DgnDbECInstanceChangeEventSource.cpp
- iModelJsNodeAddon/presentation/DgnDbECInstanceChangeEventSource.h
itwinjs-core: https://github.com/iTwin/itwinjs-core/pull/7934
Prensetation framework update UI when new changeset is applied to db. This feature was broken due to change in `applyChanges()` which was to remove any  `saveChanges()` call during `applyChanges()` to avoid saving currupt changeset. 
To provide alternative way for ECPresetnation to listen to after commit applychangeset a new event has been added to TxnMonitor that is called after apply changeset is completed and changes are commited. ECPresentation use seperate connection and thread and will not see committed changes in  `_OnAppliedChanges()`. Previously we called `saveChanges()` before `_OnAppliedChanges()` so ECPresentation could see it over its other connection. Now event `_OnAppliedChangesCommitted()` ensure `saveChanges()` …
> Fix update issue in ECPresentation where after applychangeset() it was unable to see recent changesges

- iModelCore/GeomLibs/PublicAPI/Geom/GeomApi.h
- iModelCore/GeomLibs/PublicAPI/Geom/MSBsplineSurface.h
- iModelCore/GeomLibs/PublicAPI/Geom/SolidPrimitive.h
- iModelCore/GeomLibs/PublicAPI/Regions/rg_intern.h
- iModelCore/GeomLibs/geom/src/SolidPrimitive/SolidPrimitive.cpp
- iModelCore/GeomLibs/geom/src/bspline/BSurfPatch.cpp
- iModelCore/GeomLibs/geom/src/bspline/MSBsplineSurface.cpp
- iModelCore/GeomLibs/geom/src/regions/rg_header.cpp
Follows up https://github.com/iTwin/imodel-native/pull/1076
Addresses the geomlibs portion of https://github.com/iTwin/itwinjs-backlog/issues/1473
> Geomlibs cleanup for clang/LLVM 20

- iModelCore/ECPresentation/Source/Content/PropertyInfoStore.cpp
- iModelCore/ECPresentation/Tests/NonPublished/Integration/Content/ContentIntegrationTests.cpp
Fixes https://github.com/iTwin/itwinjs-core/issues/7983
There were 2 issues:
1. If a property-specific override was found, we didn't even look at class-level overrides. That's wrong, as we should pick the override with the highest priority.
2. The "hide the rest" class-level property display overrides, which are added with lowest possible priority, were overwriting higher priority overrides that could possibly already be there.
> Presentation: Fix property overrides always taking precedence over class-based overrides

- iModelCore/ECDb/ECDb/ClassMapColumnFactory.cpp
- iModelCore/ECDb/ECDb/ClassMapColumnFactory.h
- iModelCore/ECDb/ECDb/DbMappingManager.cpp
- iModelCore/ECDb/Tests/Data/fileformatbenchmark/schemas/dgndb/BisCore.ecschema.xml
- iModelCore/ECDb/Tests/NonPublished/SchemaRemapTests.cpp
When Struct definition of structType property is updated and now it has new properties and collectively it does not fit in joined table we moved it into overflow table.
The bug was that when structType property was already in overflow table we allocated columns in joined table. Then attempt to move the whole struct to different columns in overflow table along with newly allocated joined table column.
The fix is struct that already is in overflow always allocate column in overflow table and thus its not moved at all.
> Fix issue related to struct property mapping

- iModelCore/ECDb/ECDb/ConcurrentQueryManagerImpl.cpp
- iModelCore/ECDb/Tests/NonPublished/ConcurrentQueryTest_V2.cpp
fixes: https://github.com/iTwin/itwinjs-core/issues/7984
The cleared cache did not properly clean ConcurrentQuery's internal caches, so if an identical query was sent again, the statement would be reused, which triggers an internal failsafe to protect against that.
Now we clean concurrent query caches.
@khanaffan please check. There are so many classes and caches in concurrent query, I'm only 80% sure that I hit the right spot and didn't miss anything. My added test passes after fix and fails without.
> Fix for: Clearing ECDb cache causes repeated ConcurrentQuery to fail

- iModelCore/ECDb/ECDb/SchemaWriter.cpp
- iModelCore/ECDb/Tests/NonPublished/ECDbTests.cpp
- iModelCore/ECDb/Tests/NonPublished/SchemaSyncTest.cpp
- iModelCore/ECDb/Tests/NonPublished/SchemaUpgradeTests.cpp
fixes :https://github.com/iTwin/imodel-native/issues/1078
Issue Link: https://dev.azure.com/bentleycs/ProductAdvancement/_workitems/edit/1647065
Changes made:
Enhanced existing test (CustomAttributeOrdinal) to validate that custom attributes correctly persisted in the database.
Added ECSQL query to check presence and order of applied custom attributes after schema import.
Ensured consistency of CA data after version upgrades.
Verified behavior across old and new code to confirm correctness post-fix.
> Fix constraint violation when inserting a new custom attribute

- iModelCore/GeomLibs/geom/src/bspline/BSurfPatch.cpp
- iModelCore/GeomLibs/geom/test/CurvePrimitiveTest/t_AreaBoolean.cpp
- iModelCore/GeomLibs/geom/test/CurvePrimitiveTest/t_directEvaluateSpiral.cpp
Recently updated CI Windows version (microsoftwindowsdesktop:office-365:win11-23h2-avd-m365) is causing a CI build failure in the geomlibs test introduced in https://github.com/iTwin/imodel-native/pull/721.
The test logic that is failing is moved to "long tests" scope so that we can debug when dev machines move to the new environment.
Backports will be needed:
> circumvent test failure due to new CI Windows environment

- iModelCore/iModelPlatform/DgnCore/TxnManager.cpp
- iModelCore/iModelPlatform/PublicAPI/DgnPlatform/TxnManager.h
- iModelJsNodeAddon/presentation/DgnDbECInstanceChangeEventSource.cpp
- iModelJsNodeAddon/presentation/DgnDbECInstanceChangeEventSource.h
itwinjs-core: https://github.com/iTwin/itwinjs-core/pull/8149
For 
1. PullMerge() - `TxnMonitor::_OnPullMergeEnd()` ensure saveChanges() have been called.
2. Do/Undo - `TxnMonitor::_OnUndoRedo()` ensure saveChanges() have been called.
> Fix event where ec presentation expect changes to be saved

- iModelCore/GeomLibs/geom/src/bspline/bspcurv.cpp
- Comparing doubles with exact values may not work anymore with VS 17.14
- Fix returning start/end points of rational b-spline with zero weights as zeroes
> VS 17.14 build patch: don't compare doubles with exact values

- iModelCore/iModelPlatform/DgnCore/Render.cpp
- iModelCore/iModelPlatform/DgnCore/RenderMaterial.cpp
- iModelCore/iModelPlatform/PublicAPI/DgnPlatform/RenderMaterial.h
Fixes https://github.com/iTwin/itwin-graphics-backlog/issues/681.
imodel-native-internal: https://github.com/iTwin/imodel-native-internal/pull/870
> Permit a material to not override element transparency.

- iModelCore/BeSQLite/SQLite/blockcachevfs.c
Changes come from this cloudsqlite commit: https://sqlite.org/cloudsqlite/info/5a8c00d32086439d
A future PR will update our sqlite to have all the latest changes from cloudsqlite and update our sqlite version. This one just adds the one set of changes, which as far as I can tell aren't dependent on any other changes.
> Add new entries to bcv_stat table to debug memory issue
