iModelJsNodeAddon/IModelJsNative.cpp
iModelJsNodeAddon/IModelJsNative.h

- Remove unused currentClientRequestContext
- unify use of RequireDbIsOpen
- use NapiInfoCR 
- remove unused ChangeSetKind

code cleanup

---

iModelCore/BeSQLite/SQLite/blockcachevfs.c

Fix bug allowing thread-unsafe function bcvfsWriteBlock() to be called from multiple threads simultaneously

---

iModelCore/ECPresentation/Tests/Stress/PresentationManagerStressTests.cpp
iModelCore/ECPresentation/Tests/Stress/run-stress-tests.yaml

Needed some attention after moving to GH.

Presentation: Revive stress tests

---

iModelCore/ECPresentation/Tests/Performance/Analysis/HierarchyPerformanceAnalysis.cpp
iModelCore/ECPresentation/Tests/Performance/Analysis/MultiProcessPerformanceAnalysis.cpp
iModelCore/ECPresentation/Tests/Performance/Regression/HierarchyPerformanceTests.cpp
iModelCore/ECPresentation/Tests/Performance/run-performance-tests.yaml

Needed some attention after moving to GH.

Presentation: Revive performance tests

---

TestingScripts/MemoryLeak/RunUMDH-AllTestsInSuite.py
iModelCore/BeGTest/gtest/BeGTestExe.cpp

To find out the memory leaks using UMDH, related setup is added. It will be used by our dedicated builds for issues detection.
Related: https://github.com/iTwin/imodel-native-internal/pull/49

UMDH Setup

---

iModelCore/ECPresentation/PublicAPI/ECPresentation/ECPresentationTypes.h
iModelCore/ECPresentation/Source/UpdateHandler.cpp
iModelCore/ECPresentation/Tests/NonPublished/Integration/Content/ContentIntegrationTests.cpp

Closes https://github.com/iTwin/itwinjs-backlog/issues/567

Presentation: property override fix 

---

iModelCore/ECPresentation/Source/Content/ContentSpecificationsHandler.cpp
iModelCore/ECPresentation/Tests/NonPublished/Integration/Content/ContentIntegrationTests.cpp
iModelCore/ECPresentation/Tests/NonPublished/Integration/Hierarchies/Hierarchies_InstanceFiltering.cpp

Fixes https://github.com/iTwin/imodel-native/issues/110

Presentation: Fix failing query when `ContentInstancesOfSpecificClassesSpecification` is used with `RelatedInstanceSpecification`

---

iModelCore/ECPresentation/Source/Hierarchies/HierarchiesFiltering.cpp
iModelCore/ECPresentation/Tests/NonPublished/Integration/Hierarchies/Hierarchies_InstanceFiltering.cpp

Fixes https://github.com/iTwin/imodel-native/issues/151

Presentation: Fix hierarchy level descriptor building for grouping parent nodes

---

iModelCore/ECPresentation/Source/Hierarchies/NavigationQueryBuilder.cpp
iModelCore/ECPresentation/Tests/NonPublished/Integration/Hierarchies/Hierarchies_InstanceFiltering.cpp

cherry-pick https://github.com/iTwin/imodel-native/pull/150

Presentation: Fix hierarchy level filtering with related instances

---

iModelCore/ECDb/ECDb/SchemaValidator.cpp
iModelCore/ECDb/Tests/NonPublished/SchemaRulesTests.cpp

modify ECDb to allow abstract classes to have concrete base classes

---

build/azure-pipelines.yml

Fix default itwinjs-core branch so it is imodel02

fix default itwinjs-core branch

---

iModelCore/ECPresentation/Source/Hierarchies/NavNodesCache.cpp

Broken with https://github.com/iTwin/imodel-native/pull/187.
Detected by [Presentation performance tests pipeline](https://dev.azure.com/bentleycs/iModelTechnologies/_build?definitionId=8583&_a=summary) which started timing-out.

Presentation: Fix broken hierarchies performance

---

iModelCore/iModelPlatform/DgnCore/RevisionManager.cpp

This change allows looking into failing changeset where the cause is a foreign key violation.
1. The flag can be enabled by `insert into be_local(name,val)values('DebugAllowFkViolations',1);` 
2. `PRAGMA foreign_key_check` will then give you the list of violations.

Allow debugging of bricked imodels.

---

iModelCore/ECPresentation/Tests/NonPublished/Integration/Content/Content_LocatingClasses.cpp

Closes https://github.com/iTwin/imodel-native/issues/231
Turns out the library works completely fine - it's just that our test iModel doesn't have any `ElementUniqueAspect` subclasses with visible properties. Added a test that proves this.

Presentation: Add a content sources request test for unique aspects situation

---

iModelCore/ECPresentation/Source/Shared/Queries/CustomFunctions.cpp
iModelCore/ECPresentation/Source/Shared/ValueHelpers.cpp
iModelCore/ECPresentation/Source/Shared/ValueHelpers.h
iModelCore/ECPresentation/Tests/NonPublished/Integration/Content/ContentIntegrationTests.cpp

Fixes https://github.com/iTwin/presentation/issues/129

Presentation: Handle enum property values that are not in enumeration

---

iModelCore/iModelPlatform/Tests/DgnProject/ignore_list.txt

Remove Unicode BOM marker from ignore list; it does not work as unicode file

Remove Unicode BOM marker from ignore list; it does not work as unicode file

---

.vscode/launch.json

Detailed description in https://github.com/iTwin/itwinjs-core/pull/5581
itwinjs-core: https://github.com/iTwin/itwinjs-core/tree/pmc/compact-edges
imodel-native-internal: https://github.com/iTwin/imodel-native-internal/tree/pmc/compact-edges
This only adds a new launcher config for running visualization tests on linux.

Compact edges

---

iModelJsNodeAddon/api_package/ts/src/NativeLibrary.ts

wrap import error of native addon with suggestion to install prerequisites

---

iModelCore/GeomLibs/PublicAPI/Geom/ClipPlane.h
iModelCore/GeomLibs/PublicAPI/Geom/ClipPlaneSet.h
iModelCore/GeomLibs/PublicAPI/Geom/CurveDetails.h
iModelCore/GeomLibs/PublicAPI/Geom/CurveVector.h
iModelCore/GeomLibs/geom/src/CurvePrimitive/CurveLocationDetail.cpp
iModelCore/GeomLibs/geom/src/CurvePrimitive/CurvePlaneIntersection.cpp
iModelCore/GeomLibs/geom/src/CurvePrimitive/ICurvePrimitive.cpp
iModelCore/GeomLibs/geom/src/CurvePrimitive/cp_spiral.h
iModelCore/GeomLibs/geom/src/CurvePrimitive/cv_clone.cpp
iModelCore/GeomLibs/geom/src/polyface/ClipPlane.cpp
iModelCore/GeomLibs/geom/src/polyface/ClipPlaneSet.cpp
iModelCore/GeomLibs/geom/test/PolyfaceTest/t_ClipPlaneSet.cpp
iModelCore/GeomLibs/geom/test/structsTest/t_Transform.cpp

Also fixed bunch of formatting, docs, and typos.

Added a general-purpose curve vector clipper

---

iModelCore/ECPresentation/Source/PresentationManagerImpl.cpp
iModelCore/ECPresentation/Tests/NonPublished/Integration/Content/Content_DistinctValuesTests.cpp

Closes: https://github.com/iTwin/itwinjs-core/issues/5748
itwinjs-core: https://github.com/iTwin/itwinjs-core/tree/presentation/filter-unique-values
itwinjs-core PR: https://github.com/iTwin/itwinjs-core/pull/5780

Presentation: Filtering unique values

---

iModelCore/ECDb/ECDb/ECSql/ECSqlParser.cpp
iModelCore/ECDb/ECDb/ECSql/ECSqlPreparer.cpp
iModelCore/ECDb/Tests/NonPublished/ECSqlPrepareTests.cpp
iModelCore/ECDb/Tests/NonPublished/ECSqlStatementTests.cpp

[Fail to parse RIGHT OUTER JOIN or LEFT OUTER JOIN #817](https://github.com/iTwin/itwinjs-backlog/issues/817)
Additionally added support for FULL and FULL OUTER joins

Fix for OUTER JOIN not parsing

---

build/profile-version-validation.yml

This pipeline enables its users to validate the new profile version changes.

Profile Version Validation Pipeline

---

iModelCore/iModelPlatform/PublicAPI/DgnPlatform/Render.h

These methods need to be exported for use by another project.

fix exports

---

iModelCore/ECPresentation/Source/Shared/ECSchemaHelper.cpp
iModelCore/ECPresentation/Tests/NonPublished/Integration/Content/Content_RelatedPropertiesTests.cpp
iModelCore/ECPresentation/Tests/NonPublished/Unit/Content/ContentQueryBuilderTests.cpp

Fixes https://github.com/iTwin/imodel-native/issues/459

Presentation Fix invalid content query

---

iModelCore/ECPresentation/Source/RuleSetLocater.cpp
iModelCore/ECPresentation/Tests/NonPublished/Unit/RuleSetLocaterTests.cpp
iModelJsNodeAddon/IModelJsNative.cpp
iModelJsNodeAddon/api_package/ts/src/NativeLibrary.ts

itwinjs-core: https://github.com/iTwin/itwinjs-core/pull/6030

Presentation: Supplemental ruleset registration

---

iModelJsNodeAddon/IModelJsNative.cpp
iModelJsNodeAddon/api_package/ts/src/NativeLibrary.ts

itwinjs-core: https://github.com/iTwin/itwinjs-core/pull/6036

Add `ECDb.getSchemaProps`

---

iModelJsNodeAddon/JsInteropDgnDb.cpp

Since Apple builds don't include runtime type information (RTTI), exception handlers meant to catch a specific type and its subclasses don't work right, so the subclasses have to be caught explicitly, along with a ... fallback.

Fix exception handling problem on Apple builds

---

iModelCore/ECPresentation/PublicAPI/ECPresentation/Content.h
iModelCore/ECPresentation/Source/Content/Content.cpp
iModelCore/ECPresentation/Tests/NonPublished/Integration/Content/ContentIntegrationTests.cpp
iModelCore/ECPresentation/Tests/NonPublished/Integration/Hierarchies/HierarchyIntegrationTests.cpp
iModelCore/ECPresentation/Tests/NonPublished/Unit/Content/DefaultPropertyFormatterTests.cpp

Partly fixes https://github.com/iTwin/presentation/issues/318

Presentation: Format point property values with units

---

iModelCore/ECPresentation/PublicAPI/ECPresentation/Rules/PresentationRuleSet.h
iModelCore/ECPresentation/Source/Hierarchies/HierarchiesFiltering.cpp
iModelCore/ECPresentation/Source/Hierarchies/HierarchiesFiltering.h
iModelCore/ECPresentation/Source/Hierarchies/NavNodeProviders.cpp
iModelCore/ECPresentation/Source/PresentationManagerImpl.cpp
iModelCore/ECPresentation/Source/RuleSetLocater.cpp
iModelCore/ECPresentation/Source/Rules/PresentationRuleSet.cpp
iModelCore/ECPresentation/Source/Shared/RulesPreprocessor.cpp
iModelCore/ECPresentation/Tests/NonPublished/Integration/Hierarchies/Hierarchies_InstanceFiltering.cpp

Fixes https://github.com/iTwin/imodel-native/issues/406

Presentation: Copy content modifiers from hierarchy ruleset to content ruleset when creating hierarchy level descriptor

---

iModelJsNodeAddon/api_package/ts/src/NativeLibrary.ts
iModelJsNodeAddon/presentation/ECPresentationUtils.cpp

itwinjs-core: https://github.com/iTwin/itwinjs-core/pull/6217

Presentation: Accept unit system formats as an array

---

.github/mergify.yml

add mergify config

---

iModelCore/iModelPlatform/DgnCore/ElementGeometry.cpp
iModelCore/iModelPlatform/PublicAPI/DgnPlatform/ElementGeometry.h

itwinjs-core: https://github.com/iTwin/itwinjs-core/pull/6315

Support civil use case that requires update be able to clear the geometry stream.

---

iModelCore/Bentley/BeRapidJson/PublicAPI/BeRapidJson/BeJsValue.h
iModelCore/ECPresentation/PublicAPI/ECPresentation/Content.h
iModelCore/ECPresentation/Source/Content/ContentItemBuilder.cpp
iModelCore/ECPresentation/Source/Content/ContentItemBuilder.h
iModelCore/ECPresentation/Source/Content/ContentProviders.cpp
iModelCore/ECPresentation/Source/Content/ContentQueryResultsReader.cpp
iModelCore/ECPresentation/Source/Shared/ValueHelpers.cpp
iModelCore/ECPresentation/Tests/NonPublished/Helpers/TestHelpers.cpp
iModelCore/ECPresentation/Tests/NonPublished/Integration/Content/ContentIntegrationTests.cpp
iModelCore/ECPresentation/Tests/NonPublished/Integration/Content/Content_DistinctValuesTests.cpp
iModelCore/ECPresentation/Tests/NonPublished/Integration/Content/Content_RelatedPropertiesTests.cpp
iModelCore/ECPresentation/Tests/NonPublished/Unit/Serialization/DefaultECPresentationSerializerTests.cpp
iModelJsNodeAddon/IModelJsNative.cpp
iModelJsNodeAddon/presentation/ECPresentationSerializer.cpp
iModelJsNodeAddon/presentation/ECPresentationSerializer.h
iModelJsNodeAddon/presentation/ECPresentationUtils.cpp
iModelJsNodeAddon/presentation/ECPresentationUtils.h

Part of https://github.com/iTwin/itwinjs-backlog/issues/976.
itwinjs-core: https://github.com/iTwin/itwinjs-core/pull/6327

Presentation: Optimizations for full iModel read

---

iModelCore/ECPresentation/Source/Content/ContentDescriptorBuilder.cpp
iModelCore/ECPresentation/Source/Shared/Queries/QueryExecutor.cpp
iModelCore/ECPresentation/Tests/NonPublished/Helpers/TestHelpers.h
iModelCore/ECPresentation/Tests/NonPublished/Integration/Content/Content_RelatedPropertiesTests.cpp

Fixes https://github.com/iTwin/imodel-native/issues/603

Presentation: Fix invalid content query

---

iModelCore/ECPresentation/Source/Shared/Queries/QueryBuilderHelpers.cpp
iModelCore/ECPresentation/Tests/NonPublished/Integration/Content/ContentIntegrationTests.cpp
iModelCore/ECPresentation/Tests/NonPublished/Integration/Hierarchies/HierarchyIntegrationTests.cpp

Closes https://github.com/iTwin/imodel-native/issues/602

Presentation: Allow sorting by `ECClassId` and `ECInstanceId`

---

build/azure-pipelines.yml

Changes taken from: https://github.com/iTwin/imodel-native/pull/636

Fix mend scan in release branch

---

iModelCore/BeSQLite/Tests/NonPublished/BeSQLiteDb_Test.cpp
schemas/ECStandards/StandardSchemas.delivery.mki
schemas/ECStandards/schemas/Bentley_Standard_CustomAttributes.01.14.ecschema.xml

Use the latest released version `01.14` of `Bentley_Standard_CustomAttributes` ecsstandards schema.

Consume latest released version of `Bentley_Standard_CustomAttributes` schema

---

iModelJsNodeAddon/JsLogger.cpp

Fixes https://github.com/iTwin/imodel-native/issues/706

Fix logger crash on app exit

---

iModelJsNodeAddon/presentation/ECPresentationUtils.cpp

Fixes https://github.com/iTwin/imodel-native/issues/725.
While ECPresentation library doesn't allow closing an iModel during task processing, the response is sent using `ThreadPool::CpuPool()`, which is outside of our control. This means, that an iModel may get closed before we start serializing or even in the middle of serializing the response, and we often need the iModel (or, to be more precise - it's `SchemaManager`) to serialize stuff. Closing the iModel during the process may result in a crash.
The fix is twofold:
1. When we get to serialization, where we know we need iModel's `SchemaManager`, we check to see if the schema manager is the same as we used to create the response. If not, then we know our ECObject pointers are invalid and we can't serialize it. We just send the …

Presentation: Fix a crash when serializing response after iModel is closed

---

.github/workflows/add-geometry-reviewers.yaml

Same action file is merged for iTwin:
https://github.com/iTwin/itwinjs-core/pull/6653

Created a GitHub action to add geometry reviewers

---

iModelJsNodeAddon/JsInteropDgnDb.cpp
iModelJsNodeAddon/api_package/ts/src/test/DgnDb.test.ts

itwinjs-core: https://github.com/iTwin/itwinjs-core/pull/6690

Include class Id in EntityMetaDataProps

---

iModelCore/GeomLibs/serialization/src/FlatBuffer/FixedStructs.cpp

itwinjs-core: https://github.com/iTwin/itwinjs-core/pull/6789

Fixed the place curve issue (through points tool) in FixedStructs.cpp

---

iModelCore/ECDb/ECDb/SchemaSync.cpp

SchemaSync utilizes data in the ec_* tables to manage all data tables. It employs this data to create, alter, add columns, and create or update indexes.
For non-tracked tables, the implementation involves copying DDLs from sqlite_master and executing them to create any missing meta tables, although it does not distinguish between meta and ec tables. This serves as future-proofing; otherwise, meta tables are generated by profile upgrades and recorded in the changeset. I have not removed the implementation but have modified it to skip over errors.
I will log an item for it so that we can enhance this functionality in the future.

SchemaSync: Skip over failing DDL for untracked meta tables 

---

iModelCore/ECPresentation/Source/UpdateHandler.cpp

Another one for https://github.com/iTwin/imodel-native/issues/750

Presentation: Ensure `IUpdateRecordsHandler::Finish` is called even if an error is thrown during update

---

iModelCore/ecobjects/test/NonPublished/SchemaDeserializationTests.cpp

Fixes https://github.com/iTwin/itwinjs-backlog/issues/979

Updated prune schemas test to check all schemas

---

iModelCore/ECDb/CHANGES.md
iModelCore/ECDb/ECDb/ECDbImpl.cpp
iModelCore/ECDb/ECDb/ECSql/ECSqlPragmas.cpp
iModelCore/ECDb/ECDb/ECSql/ECSqlPragmas.h
iModelCore/ECDb/ECDb/ECSql/PragmaECSqlPreparedStatement.cpp
iModelCore/ECDb/ECDb/IntegrityChecker.h
iModelCore/ECDb/ECDb/IssueReporter.cpp
iModelCore/ECDb/ECDb/IssueReporter.h
iModelCore/ECDb/PublicAPI/ECDb/ECDb.h
iModelCore/ECDb/Tests/NonPublished/ECDbTests.cpp
iModelCore/ECDb/Tests/NonPublished/ECSqlPragmasTests.cpp
iModelCore/ECDb/Tests/NonPublished/RelationshipTests.cpp

Fixes https://github.com/iTwin/itwinjs-backlog/issues/1097

Add new pragma function to purge orphaned link table relationships

---

TestingScripts/MemoryLeak/RunUMDH-AllTestsInSuite.py
iModelCore/ECDb/ECDb/ClassViews.cpp
iModelCore/ECDb/ECDb/ClassViews.h
iModelCore/ECDb/ECDb/InstanceReaderImpl.cpp
iModelCore/ECDb/ECDb/InstanceReaderImpl.h
iModelCore/ECDb/PublicAPI/ECDb/InstanceReader.h
iModelCore/ECDb/Tests/NonPublished/ClassViewsTests.cpp
iModelCore/ECDb/Tests/NonPublished/InstanceReaderTest.cpp
iModelCore/ECDb/Tests/NonPublished/IntegrityCheckerTests.cpp
iModelCore/ECDb/Tests/NonPublished/MockHubApi.h
iModelCore/ECPresentation/PublicAPI/ECPresentation/PresentationQuery.h
iModelCore/iModelPlatform/Tests/DgnProject/NonPublished/SchemaRemap_Test.cpp

Found when merging from imodel-native to imodel02.

Fix copyright messages

---

build/azure-pipelines.yml

imodel-native-internal: https://github.com/iTwin/imodel-native-internal/pull/589

Update azure-pipelines yml for release/4.8.x

---

build/azure-pipelines.yml

Updates yml for release of 4.9.x

Update yml for release

---

iModelCore/ECDb/Tests/Performance/PerformancePragmaStatements.cpp

Resolves https://github.com/iTwin/itwinjs-backlog/issues/1181

Added performance test for purge_orphan_relationships pragma

---

iModelCore/ECPresentation/Source/Content/ContentDescriptorBuilder.cpp
iModelCore/ECPresentation/Source/Hierarchies/NavNodeProviders.cpp
iModelCore/ECPresentation/Source/Shared/CustomizationHelper.cpp
iModelCore/ECPresentation/Source/Shared/ECExpressions/ECExpressionContextsProvider.cpp
iModelCore/ECPresentation/Source/Shared/ECExpressions/ECExpressionContextsProvider.h
iModelCore/ECPresentation/Source/Shared/Queries/CustomFunctions.cpp

Closes https://github.com/iTwin/imodel-native/issues/880

Update calculated property error description

---

build/azure-pipelines.yml

imodel-native-internal PR: https://github.com/iTwin/imodel-native-internal/pull/647

release 4.10.x yaml update

---

iModelJsNodeAddon/api_package/installNativePlatform.js
iModelJsNodeAddon/installnativeplatformMacOS.sh
iModelJsNodeAddon/makePackages.py

Remove macOS X64 support from install scripts.

macOS X64 install removals

---

iModelCore/ECDb/ECDb/ConcurrentQueryManagerImpl.cpp
iModelCore/ECDb/Tests/NonPublished/ConcurrentQueryTest_V2.cpp
iModelCore/Units/tests/NonPublished/FormattingTests.cpp

https://github.com/iTwin/imodel-native/pull/901

added newline to formatQuery wrapper with tests (#901)

---

iModelCore/ECPresentation/Source/Content/ContentProviders.cpp
iModelCore/ECPresentation/Tests/NonPublished/Unit/Content/ContentProviderTests.cpp
iModelCore/GeomLibs/PublicAPI/Geom/GeomApi.h
iModelCore/GeomLibs/PublicAPI/Geom/SolidPrimitive.h
iModelCore/GeomLibs/geom/src/bspline/MSBsplineSurface.cpp
iModelCore/GeomLibs/geom/src/regions/rg_header.cpp
iModelCore/GeomLibs/vu/src/PolygonArray.cpp
iModelCore/ecobjects/src/ECValue.cpp
iModelCore/ecobjects/src/StandaloneECInstance.cpp
iModelCore/iModelPlatform/DgnCore/RangeIndex.cpp
iModelCore/iModelPlatform/DgnCore/linestyle/StrokePattern.cpp
iModelCore/iModelPlatform/PublicAPI/DgnPlatform/DgnCategory.h
iModelCore/libsrc/crashpad/vendor/util/file/filesystem.h

I fixed the things that were easy, and left some TODO comments for the things that require additional work.
I created a new story to work off the remaining items: https://github.com/iTwin/itwinjs-backlog/issues/1473

Fixes for Clang/LLVM 20 detected problems

---

iModelCore/ecobjects/test/run-performance-tests.yaml

Use main branch for performance tests schedule

Use main branch for performance tests schedule

---

iModelCore/BeSQLite/SQLite/bentley-sqlite.c
iModelCore/BeSQLite/Tests/NonPublished/BeSQLiteDb_Test.cpp

closes: https://github.com/iTwin/itwinjs-backlog/issues/1504
itwinjs-core: https://github.com/iTwin/itwinjs-core/pull/8112

Session extension could not prepare a SQL to apply change due to reaching max parse depth

---

iModelCore/ecobjects/test/Performance/PerformanceECJsonTests.cpp
iModelCore/ecobjects/test/Performance/PerformanceECXmlTests.cpp

Use units schema version 01.00.09

Fix ecobjects performance tests

---

iModelCore/ECPresentation/Source/Rules/RelatedPropertiesSpecification.cpp
iModelCore/ECPresentation/Tests/NonPublished/Integration/Content/ContentIntegrationTests.cpp

Fixes https://github.com/iTwin/itwinjs-core/issues/8353
We only want to apply content modifiers with `applyOnNestedContent = true` if nested content (related instance properties) was loaded with "all properties" request. E.g. if only a few specific properties are requested - we don't want to apply those extra content modifiers.
However, our check if related properties are loaded as "all properties" was flawed - there had to be 1 specification with very specific attributes for the condition to pass. This meant that hiding one property and requesting to load everything else would not pass. Also, loading everything with some extra overrides wouldn't pass either.
The change should fix these issues.

Presentation: Fix content modifiers with `applyOnNestedContent` not being applied when they should

---

iModelJsNodeAddon/JsCloudSqlite.cpp
iModelJsNodeAddon/api_package/ts/src/NativeCloudSqlite.ts

itwinjs-core: https://github.com/iTwin/itwinjs-core/pull/8443

Expose the memory_used and memory_highwater APIs from SQLite.

---

iModelCore/ECPresentation/Source/Shared/Queries/CustomFunctions.cpp
iModelCore/ECPresentation/Tests/NonPublished/Integration/Content/ContentIntegrationTests.cpp

Fixes https://github.com/iTwin/itwinjs-backlog/issues/1589

Presentation: Fix `EvaluateECExpression` causing a crash or erroring-out when the resulting value is undefined or null

---

.vscode/launch.json
iModelCore/BeSQLite/BeBriefcaseBasedIdSequence.cpp
iModelCore/BeSQLite/BeSQLite.cpp
iModelCore/BeSQLite/ChangeSet.cpp
iModelCore/BeSQLite/PublicAPI/BeSQLite/BeBriefcaseBasedIdSequence.h
iModelCore/BeSQLite/PublicAPI/BeSQLite/BeSQLite.h
iModelCore/BeSQLite/PublicAPI/BeSQLite/ChangeSet.h
iModelCore/BeSQLite/Tests/NonPublished/BeSQLiteDb_Test.cpp
iModelCore/ECDb/ECDb/ECDbImpl.cpp
iModelCore/ECDb/PublicAPI/ECDb/ECDb.h
iModelCore/ECDb/Tests/NonPublished/MockHubApi.cpp
iModelCore/iModelPlatform/DgnCore/ChangesetTxns.cpp
iModelCore/iModelPlatform/DgnCore/DgnDb.cpp
iModelCore/iModelPlatform/DgnCore/TxnManager.cpp
iModelCore/iModelPlatform/PublicAPI/DgnPlatform/TxnManager.h
iModelJsNodeAddon/IModelJsNative.cpp
iModelJsNodeAddon/api_package/ts/src/NativeLibrary.ts
iModelJsNodeAddon/api_package/ts/src/test/ElementDependency.test.ts

This reverts commit 9df933fee0d862824167e5687cdb006f6236a3aa.
#1213 merged but the accompanying https://github.com/iTwin/itwinjs-core/pull/8522 did not merge and is not ready to.
itwinjs-core master branch no longer builds.
@khanaffan, please submit a new PR with the reverted changes.

Revert "Improve rebase for multi-user workflow (#1213)"

---

.vscode/launch.json
iModelCore/BeSQLite/BeBriefcaseBasedIdSequence.cpp
iModelCore/BeSQLite/BeSQLite.cpp
iModelCore/BeSQLite/ChangeSet.cpp
iModelCore/BeSQLite/PublicAPI/BeSQLite/BeBriefcaseBasedIdSequence.h
iModelCore/BeSQLite/PublicAPI/BeSQLite/BeSQLite.h
iModelCore/BeSQLite/PublicAPI/BeSQLite/ChangeSet.h
iModelCore/BeSQLite/Tests/NonPublished/BeSQLiteDb_Test.cpp
iModelCore/ECDb/ECDb/ECDbImpl.cpp
iModelCore/ECDb/PublicAPI/ECDb/ECDb.h
iModelCore/ECDb/Tests/NonPublished/MockHubApi.cpp
iModelCore/iModelPlatform/DgnCore/ChangesetTxns.cpp
iModelCore/iModelPlatform/DgnCore/DgnDb.cpp
iModelCore/iModelPlatform/DgnCore/TxnManager.cpp
iModelCore/iModelPlatform/PublicAPI/DgnPlatform/TxnManager.h
iModelJsNodeAddon/IModelJsNative.cpp
iModelJsNodeAddon/api_package/ts/src/NativeLibrary.ts
iModelJsNodeAddon/api_package/ts/src/test/ElementDependency.test.ts

This reverts commit 516a4216c06e20f3fae8bcd024536fbfc6c796fc.

Reapply "Improve rebase for multi-user workflow (#1213)" (#1214)
